/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { IEnumValue } from "./enum.value";

/**
 * An object defining the values of an enum.
 */
export interface IEnum {
    /**
     * The name of the enum, e.g. for display purposes.
     */
    name?: string;
    /**
     * The description of the enum.
     */
    description?: string;
    /**
     * The type of the integer enum value.
     */
    valueType?: "INT8" | "UINT8" | "INT16" | "UINT16" | "INT32" | "UINT32" | "INT64" | "UINT64" | string;
    /**
     * An array of enum values. Duplicate names or duplicate integer values are not allowed.
     *
     * @minItems 1
     */
    values: [IEnumValue, ...IEnumValue[]];
    [k: string]: unknown;
}
