import * as BABYLON from "@babylonjs/core";
import * as GUI from "@babylonjs/gui";
import { EventState, Observable, Observer, PropertyChangedEventArgs } from "core/events";
import { IGeo2 } from "core/geography";
import { Size2 } from "core/geometry";
import { Context2DTileMap, ICanvasRenderingOptions, InputsNavigationTarget } from "core/map";
import { IImageTileMapLayer, IPipelineMessageType, ITile, ITileDisplay, ITileMap, ITileMetrics, ITileNavigationApi, ITileNavigationState, ImageLayer } from "core/tiles";
import { Nullable } from "core/types";
import { ControlInputController } from "./control.inputs";
import { RGBAColor } from "core/math";
export type ControlTileContentType = HTMLImageElement;
export interface IMapControlOptions extends ICanvasRenderingOptions {
    navigationManager?: InputsNavigationTarget<MapControl>;
    inputController?: ControlInputController<MapControl>;
}
export declare class MapControl extends GUI.Container implements ITileDisplay, ITileNavigationApi<MapControl>, ITileMap<ControlTileContentType, IImageTileMapLayer> {
    static DefaultBackground: RGBAColor;
    static DefaultOptions: ICanvasRenderingOptions;
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<ITileDisplay, unknown>>;
    _map: Context2DTileMap;
    _mapValidationObserver: Nullable<Observer<boolean>>;
    _cachedMeasure: Size2;
    _navigationManager: InputsNavigationTarget<MapControl>;
    _inputController: ControlInputController<MapControl>;
    constructor(name: string, options?: IMapControlOptions, nav?: ITileNavigationState);
    get displayHeight(): number;
    get displayWidth(): number;
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<ITileDisplay, unknown>>;
    get ratio(): number;
    dispose(): void;
    setView(center: IGeo2 | Array<number>, zoom?: number, rotation?: number): MapControl;
    zooming(delta: number): MapControl;
    zoomIn(delta: number): MapControl;
    zoomOut(delta: number): MapControl;
    translatePixel(tx: number, ty: number, metrics?: ITileMetrics): MapControl;
    translate(lat: IGeo2 | Array<number> | number, lon?: number): MapControl;
    rotate(r: number): MapControl;
    get navigation(): ITileNavigationState;
    get layerAddedObservable(): Observable<IImageTileMapLayer>;
    get layerRemovedObservable(): Observable<IImageTileMapLayer>;
    getLayers(predicate?: (l: IImageTileMapLayer) => boolean, sorted?: boolean): IterableIterator<IImageTileMapLayer>;
    addLayer(layer: ImageLayer): void;
    removeLayer(layer: ImageLayer): void;
    private _onMapValidation;
    protected _additionalProcessing(parentMeasure: GUI.Measure, context: BABYLON.ICanvasRenderingContext): void;
    protected _localDraw(context: BABYLON.ICanvasRenderingContext): void;
    added(eventData: IPipelineMessageType<ITile<ControlTileContentType>>, eventState: EventState): void;
    removed(eventData: IPipelineMessageType<ITile<ControlTileContentType>>, eventState: EventState): void;
    updated(eventData: IPipelineMessageType<ITile<ControlTileContentType>>, eventState: EventState): void;
    protected _onTileAdded(eventData: Array<ITile<ControlTileContentType>>, eventState: EventState): void;
    protected _onTileRemoved(eventData: Array<ITile<ControlTileContentType>>, eventState: EventState): void;
    protected _onTileUpdated(eventData: Array<ITile<ControlTileContentType>>, eventState: EventState): void;
}
