import { ParametricValue } from "./math";
export declare class RGBAColor {
    static aliceblue: RGBAColor;
    static antiquewhite: RGBAColor;
    static aqua: RGBAColor;
    static aquamarine: RGBAColor;
    static azure: RGBAColor;
    static beige: RGBAColor;
    static bisque: RGBAColor;
    static black: RGBAColor;
    static blanchedalmond: RGBAColor;
    static blue: RGBAColor;
    static blueviolet: RGBAColor;
    static brown: RGBAColor;
    static burlywood: RGBAColor;
    static cadetblue: RGBAColor;
    static chartreuse: RGBAColor;
    static chocolate: RGBAColor;
    static coral: RGBAColor;
    static cornflowerblue: RGBAColor;
    static cornsilk: RGBAColor;
    static crimson: RGBAColor;
    static cyan: RGBAColor;
    static darkblue: RGBAColor;
    static darkcyan: RGBAColor;
    static darkgoldenrod: RGBAColor;
    static darkgray: RGBAColor;
    static darkgreen: RGBAColor;
    static darkgrey: RGBAColor;
    static darkkhaki: RGBAColor;
    static darkmagenta: RGBAColor;
    static darkolivegreen: RGBAColor;
    static darkorange: RGBAColor;
    static darkorchid: RGBAColor;
    static darkred: RGBAColor;
    static darksalmon: RGBAColor;
    static darkseagreen: RGBAColor;
    static darkslateblue: RGBAColor;
    static darkslategray: RGBAColor;
    static darkslategrey: RGBAColor;
    static darkturquoise: RGBAColor;
    static darkviolet: RGBAColor;
    static deeppink: RGBAColor;
    static deepskyblue: RGBAColor;
    static dimgray: RGBAColor;
    static dimgrey: RGBAColor;
    static dodgerblue: RGBAColor;
    static firebrick: RGBAColor;
    static floralwhite: RGBAColor;
    static forestgreen: RGBAColor;
    static fuchsia: RGBAColor;
    static gainsboro: RGBAColor;
    static ghostwhite: RGBAColor;
    static gold: RGBAColor;
    static goldenrod: RGBAColor;
    static gray: RGBAColor;
    static green: RGBAColor;
    static greenyellow: RGBAColor;
    static grey: RGBAColor;
    static honeydew: RGBAColor;
    static hotpink: RGBAColor;
    static indianred: RGBAColor;
    static indigo: RGBAColor;
    static ivory: RGBAColor;
    static khaki: RGBAColor;
    static lavender: RGBAColor;
    static lavenderblush: RGBAColor;
    static lawngreen: RGBAColor;
    static lemonchiffon: RGBAColor;
    static lightblue: RGBAColor;
    static lightcoral: RGBAColor;
    static lightcyan: RGBAColor;
    static lightgoldenrodyellow: RGBAColor;
    static lightgray: RGBAColor;
    static lightgreen: RGBAColor;
    static lightgrey: RGBAColor;
    static lightpink: RGBAColor;
    static lightsalmon: RGBAColor;
    static lightseagreen: RGBAColor;
    static lightskyblue: RGBAColor;
    static lightslategray: RGBAColor;
    static lightslategrey: RGBAColor;
    static lightsteelblue: RGBAColor;
    static lightyellow: RGBAColor;
    static lime: RGBAColor;
    static limegreen: RGBAColor;
    static linen: RGBAColor;
    static magenta: RGBAColor;
    static maroon: RGBAColor;
    static mediumaquamarine: RGBAColor;
    static mediumblue: RGBAColor;
    static mediumorchid: RGBAColor;
    static mediumpurple: RGBAColor;
    static mediumseagreen: RGBAColor;
    static mediumslateblue: RGBAColor;
    static mediumspringgreen: RGBAColor;
    static mediumturquoise: RGBAColor;
    static mediumvioletred: RGBAColor;
    static midnightblue: RGBAColor;
    static mintcream: RGBAColor;
    static mistyrose: RGBAColor;
    static moccasin: RGBAColor;
    static navajowhite: RGBAColor;
    static navy: RGBAColor;
    static oldlace: RGBAColor;
    static olive: RGBAColor;
    static olivedrab: RGBAColor;
    static orange: RGBAColor;
    static orangered: RGBAColor;
    static orchid: RGBAColor;
    static palegoldenrod: RGBAColor;
    static palegreen: RGBAColor;
    static paleturquoise: RGBAColor;
    static palevioletred: RGBAColor;
    static papayawhip: RGBAColor;
    static peachpuff: RGBAColor;
    static peru: RGBAColor;
    static pink: RGBAColor;
    static plum: RGBAColor;
    static powderblue: RGBAColor;
    static purple: RGBAColor;
    static red: RGBAColor;
    static rosybrown: RGBAColor;
    static royalblue: RGBAColor;
    static saddlebrown: RGBAColor;
    static salmon: RGBAColor;
    static sandybrown: RGBAColor;
    static seagreen: RGBAColor;
    static seashell: RGBAColor;
    static sienna: RGBAColor;
    static silver: RGBAColor;
    static skyblue: RGBAColor;
    static slateblue: RGBAColor;
    static slategray: RGBAColor;
    static slategrey: RGBAColor;
    static snow: RGBAColor;
    static springgreen: RGBAColor;
    static steelblue: RGBAColor;
    static tan: RGBAColor;
    static teal: RGBAColor;
    static thistle: RGBAColor;
    static tomato: RGBAColor;
    static turquoise: RGBAColor;
    static violet: RGBAColor;
    static wheat: RGBAColor;
    static white: RGBAColor;
    static whitesmoke: RGBAColor;
    static yellow: RGBAColor;
    static yellowgreen: RGBAColor;
    static CSSMap: Map<string, RGBAColor>;
    static White(): RGBAColor;
    static Black(): RGBAColor;
    static LightGray(): RGBAColor;
    static Gray(): RGBAColor;
    static CoolSteelBlue(): RGBAColor;
    static ElectricBlue(): RGBAColor;
    static NeonBlue(): RGBAColor;
    static h2r(hex: string): Array<number> | undefined;
    static r2h(rgb: Array<number>): string;
    static Parse(str: string): RGBAColor;
    private _r;
    private _g;
    private _b;
    private _a;
    constructor(r: number | RGBAColor, g?: number, b?: number, a?: number);
    get r(): number;
    get g(): number;
    get b(): number;
    get a(): number;
    set r(value: number);
    set g(value: number);
    set b(value: number);
    set a(value: number);
    toHexString(): string;
    toHSL(): HSLColor;
    interpolate(color: RGBAColor, t: ParametricValue, keepAlpha?: boolean): RGBAColor;
    interpolateInPlace(color: RGBAColor, t: ParametricValue, keepAlpha?: boolean): RGBAColor;
    toString(): string;
}
export declare class HSLColor {
    h: number;
    s: number;
    l: number;
    private static hue2rgb;
    constructor(h: number, s: number, l: number);
    toRGB(): RGBAColor;
}
