/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { IRootProperty } from "../common/rootProperty";

/**
 * A set of semantics containing per-tile and per-feature values defining the position and appearance properties for features in a tile.
 */
export type FeatureTable = IRootProperty;

/**
 * A `BinaryBodyReference` object defining the reference to a section of the binary body where the property values are stored. Details about this property are described in the 3D Tiles specification.
 */
export interface IBinaryBodyReference {
    /**
     * The datatype of components in the property. This is defined only if the semantic allows for overriding the implicit component type. These cases are specified in each tile format.
     */
    componentType?: "BYTE" | "UNSIGNED_BYTE" | "SHORT" | "UNSIGNED_SHORT" | "INT" | "UNSIGNED_INT" | "FLOAT" | "DOUBLE" | string;
    [k: string]: unknown;
}

/**
 * An object defining the offset into a section of the binary body of the features table where the property values are stored if not defined directly in the JSON.
 */
export interface IBinaryBodyOffset {
    /**
     * The offset into the buffer in bytes.
     */
    byteOffset: number;
}

/**
 * A user-defined property which specifies application-specific metadata in a tile. Values can refer to sections in the binary body with a `BinaryBodyReference` object. Global values can be also be defined directly in the JSON.
 */
export type Property = IBinaryBodyReference | GlobalPropertyBoolean | GlobalPropertyInteger | GlobalPropertyNumber | GlobalPropertyCartesian3 | GlobalPropertyCartesian4;

/**
 * An object defining a global boolean property value for all features.
 */
export type GlobalPropertyBoolean = boolean;
/**
 * A `GlobalPropertyInteger` object defining an integer property for all points. Details about this property are described in the 3D Tiles specification.
 */
export type GlobalPropertyInteger = IBinaryBodyOffset | number;
/**
 * An object defining a global numeric property value for all features.
 */
export type GlobalPropertyNumber = IBinaryBodyOffset | number;
/**
 * A `GlobalPropertyCartesian3` object defining a 3-component numeric property for all points. Details about this property are described in the 3D Tiles specification.
 */
export type GlobalPropertyCartesian3 = IBinaryBodyOffset | [number, number, number];
/**
 * A `GlobalPropertyCartesian4` object defining a 4-component numeric property for all points. Details about this property are described in the 3D Tiles specification.
 */
export type GlobalPropertyCartesian4 = IBinaryBodyOffset | [number, number, number, number];
