import { ICanvasRenderingContext } from "@babylonjs/core";
import { Control, Measure } from "@babylonjs/gui";
import { Observable, Observer } from "core/events";
import { IGeo2 } from "core/geography";
import { ITileNavigationState, ITileMap, ITileMapLayer, ITileDisplay } from "core/tiles";
import { Nullable } from "core/types";
export type ControlTileContentType = HTMLImageElement;
export declare class MapControl extends Control implements ITileMap<ControlTileContentType>, ITileDisplay {
    _layerAddedObservable?: Observable<ITileMapLayer<ControlTileContentType>>;
    _layerRemovedObservable?: Observable<ITileMapLayer<ControlTileContentType>>;
    protected _navigation: ITileNavigationState;
    protected _layers?: Map<string, ITileMapLayer<ControlTileContentType>>;
    protected _orderedLayers?: ITileMapLayer<ControlTileContentType>[];
    protected _background: string;
    _navigationUpdatedObserver?: Nullable<Observer<ITileNavigationState>>;
    constructor(name: string, nav?: ITileNavigationState);
    get displayHeight(): number;
    get displayWidth(): number;
    get background(): string;
    set background(value: string);
    get layerAddedObservable(): Observable<ITileMapLayer<ControlTileContentType>>;
    get layerRemovedObservable(): Observable<ITileMapLayer<ControlTileContentType>>;
    get navigation(): ITileNavigationState;
    getLayers(predicate?: (l: ITileMapLayer<ControlTileContentType>) => boolean, sorted?: boolean): IterableIterator<ITileMapLayer<ControlTileContentType>>;
    getOrderedLayers(predicate?: (l: ITileMapLayer<ControlTileContentType>) => boolean): IterableIterator<ITileMapLayer<ControlTileContentType>>;
    addLayer(layer: ITileMapLayer<ControlTileContentType>): void;
    removeLayer(layer: ITileMapLayer<ControlTileContentType>): void;
    dispose(): void;
    setView(center?: IGeo2 | Array<number>, zoom?: number, rotation?: number): MapControl;
    zooming(delta: number): MapControl;
    zoomIn(delta: number): MapControl;
    zoomOut(delta: number): MapControl;
    translatePixel(tx: number, ty: number): MapControl;
    translate(lat: IGeo2 | Array<number> | number, lon?: number): MapControl;
    rotate(r: number): MapControl;
    private _addSortedLayer;
    private _removeSortedLayer;
    private _onNavigationUpdatedInternal;
    private _updateLayersContext;
    private _bindNavigation;
    private _updateNavigationBounds;
    _draw(ctx: ICanvasRenderingContext, invalidatedRectangle?: Nullable<Measure>): void;
    protected _drawLayer(ctx: ICanvasRenderingContext, layer: ITileMapLayer<ControlTileContentType>): void;
    protected _onNavigationUnbinded(nav?: ITileNavigationState): void;
    protected _onNavigationBinded(nav?: ITileNavigationState): void;
    protected _onLayerAdded(layer: ITileMapLayer<ControlTileContentType>): void;
    protected _onLayerRemoved(layer: ITileMapLayer<ControlTileContentType>): void;
    protected _onNavigationUpdated(event: ITileNavigationState): void;
}
