import { Nullable } from "../../types";
import { ILinkOptions, IPipelineMessageType, ISourceBlock, ITargetBlock, ITilePipelineLink } from "./tiles.pipeline.interfaces";
import { EventState, Observer } from "../../events/events.observable";

/// <summary>
/// In order to keep the system modular and flexible, the Tile Pipeline is designed to be a chain of components, each with a specific role and responsibility.
/// To avoid complexity using several different interfaces, the pipeline will leverage the Observable pattern only. The overhead of using the Observable pattern is not significant
/// because of the low number of events that will be generated by the system.
/// This class is encompass the pattern into a link object which is listenning from observable events from a source and forward them to a target.
/// </summary>
export class TilePipelineLink<T> implements ITilePipelineLink<T> {
    _source: ISourceBlock<T>;
    _target: ITargetBlock<T>;
    _options?: ILinkOptions;

    _updatedObserver: Nullable<Observer<IPipelineMessageType<T>>>;
    _addedObserver: Nullable<Observer<IPipelineMessageType<T>>>;
    _removedObserver: Nullable<Observer<IPipelineMessageType<T>>>;

    public constructor(source: ISourceBlock<T>, target: ITargetBlock<T>, options?: ILinkOptions) {
        this._source = source;
        this._target = target;
        this._options = options;

        this._addedObserver = source.addedObservable.add(this._onAdded.bind(this));
        this._removedObserver = source.removedObservable.add(this._onRemoved.bind(this));
        this._updatedObserver = source.updatedObservable.add(this._onUpdated.bind(this));
    }

    public get source(): ISourceBlock<T> {
        return this._source;
    }

    public get target(): ITargetBlock<T> {
        return this._target;
    }

    public get options(): ILinkOptions | undefined {
        return this._options;
    }

    public dispose(): void {
        this._addedObserver?.disconnect();
        this._removedObserver?.disconnect();
        this._updatedObserver?.disconnect();
        this._addedObserver = null;
        this._removedObserver = null;
        this._updatedObserver = null;
    }

    protected _onAdded(eventData: IPipelineMessageType<T>, eventState: EventState): void {
        eventState.currentTarget = this; // ensure the target is set
        this._target?.added(eventData, eventState);
    }

    protected _onRemoved(eventData: IPipelineMessageType<T>, eventState: EventState): void {
        eventState.currentTarget = this; // ensure the target is set
        this._target?.removed(eventData, eventState);
    }

    protected _onUpdated(eventData: IPipelineMessageType<T>, eventState: EventState): void {
        eventState.currentTarget = this; // ensure the target is set
        this._target?.updated(eventData, eventState);
    }
}
