import { Observable } from "../../events/events.observable";
import { IDisposable, Nullable } from "../../types";
import { ITile, ITileAddress, ITileAddressProcessor, ITileBuilder, ITileDatasource, ITileMetricsProvider, TileContent } from "../tiles.interfaces";
import { ISize2 } from "../../geometry/geometry.interfaces";
import { ITileNavigationState } from "../navigation/tiles.navigation.interfaces";
import { PropertyChangedEventArgs } from "../../events/events.args";

export interface ITilePipelineComponent extends IDisposable {
    id?: string;
}

export interface ITileDisplay extends ISize2, IDisposable {
    resizeObservable: Observable<PropertyChangedEventArgs<ITileDisplay, ISize2>>;
    setSize(w: number, h: number): ITileDisplay;
}

export interface ITileContentProvider<T> extends ITileMetricsProvider, IDisposable {
    name: string;
    datasource: ITileDatasource<T, ITileAddress>;
    accept(address: ITileAddress): boolean;
    fetchContentAsync(address: ITileAddress, ...userArgs: Array<unknown>): Promise<Nullable<TileContent<T>>>;
}

export interface ITileSystem<T> extends ITileMetricsProvider {
    name: string;
    addressProcessor?: ITileAddressProcessor;
    provider: ITileContentProvider<T>;
    factory: ITileBuilder<T>;
}

/// <summary>
/// The View component is tasked with selecting appropriate tile addresses, guided by the Tile Metrics and navigation properties. Its role is expanded to include the following:
/// - Tile Selection Based on Navigation Properties: Considers the geographic center, azimuth, and level of detail in tile selection, ensuring relevance and accuracy.
/// - Dimension and Scalability: Defines the dimension in unitless TileXY units, enabling flexibility and adaptability to different screen sizes and resolutions.
/// - Event Management Through Observable Pattern: Crucially, the View is responsible for managing events using the observable pattern. It sends notifications about 'Added'
///   and 'Removed' TileAddresses, allowing other components of the system to react and update accordingly. This feature is vital for ensuring that the system remains dynamic
///   and responsive to changes, such as user navigation or zoom adjustments.
/// </summary>
export interface ITileView<T> extends ITilePipelineComponent {
    addressAddedObservable: Observable<Array<ITileAddress>>;
    addressRemovedObservable: Observable<Array<ITileAddress>>;
    state: Nullable<ITileNavigationState>;
    display: Nullable<ITileDisplay>;
}

/// <summary>
/// The TileProvider acts as a critical intermediary between the View and the TileContentProvider. Its responsibilities include:
/// - Observing View Events: The TileProvider is tasked with observing events generated by the View, particularly those related to tile addition or removal.
/// - Synchronization with TileContentProvider: Upon receiving events from the View, the TileProvider synchronizes these with the TileContentProvider.
///   This synchronization ensures that the content of the tiles is in line with the changes in the View.
/// - Managing Tile Events: Once the TileContent is ready, the TileProvider takes over the role of event management. It uses the observable pattern
///   to handle 'Add', 'Remove', and 'Update' tile events. The 'Update' event is particularly significant in the context of asynchronous content loading,
///   allowing the system to dynamically update tiles as new content becomes available or as user interactions necessitate changes.
///   IMPORTANT : The Metrics is UNIQUE for a given ITileProvider, wich mean any of the ITileSystem registered in the ITileProvider will share the same metrics.
/// </summary>
export interface ITileProvider<T> extends ITilePipelineComponent, ITileMetricsProvider {
    /// <summary> messaged when a tile is updated </summary>
    tileUpdatedObservable: Observable<Array<ITile<T>>>;

    /// <summary> messaged when a tile is added </summary>
    tileAddedObservable: Observable<Array<ITile<T>>>;

    /// <summary> messaged when a tile is removed </summary>
    tileRemovedObservable: Observable<Array<ITile<T>>>;

    /// <summary>
    /// Get tiles using one address. Typically used by the pipeline, this method is using the underlying providers,
    /// first to verify if the content provider are accepting the address, and then ask for the contents itself.
    /// </summary>
    getTile(address: ITileAddress, ...userArgs: Array<unknown>): Nullable<ITile<T>[]>;

    /// <summary> register a content provider to the pipeline </summary>
    addContentProvider<P extends T>(system: ITileSystem<P>): void;

    /// <summary> unregister a content provider from the pipeline </summary>
    removeContentProvider(name: string): void;

    /// <summary> get a content provider from the pipeline using is name. Name is usually comming from ITile.namespace. </summary>
    getContentProviderByName<P extends T>(name: string): ITileSystem<P> | undefined;
}

export interface ITileConsumer<T> extends ITilePipelineComponent {
    providerChangedObservable: Observable<PropertyChangedEventArgs<ITileConsumer<T>, ITileProvider<T>>>;
    provider?: ITileProvider<T>;
}
