import { Nullable } from "../../types";
import { ILinkOptions, IPipelineMessageType, ISourceBlock, ITargetBlock, ITilePipelineLink } from "./tiles.pipeline.interfaces";
import { EventState, Observer } from "../../events/events.observable";

/// <summary>
/// In order to keep the system modular and flexible, the Tile Pipeline is designed to be a chain of components, each with a specific role and responsibility.
/// To avoid complexity using several different interfaces, the pipeline will leverage the Observable pattern only. The overhead of using the Observable pattern is not significant
/// because of the low number of events that will be generated by the system.
/// This class is encompass the pattern into a link object which is listenning from observable events from a source and forward them to a target.
/// </summary>
export class TilePipelineLink<T> implements ITilePipelineLink<T> {
    _source: ISourceBlock<T>;
    _target: ITargetBlock<T>;
    _options?: ILinkOptions<T>;

    _updatedObserver: Nullable<Observer<IPipelineMessageType<T>>>;
    _addedObserver: Nullable<Observer<IPipelineMessageType<T>>>;
    _removedObserver: Nullable<Observer<IPipelineMessageType<T>>>;

    public constructor(source: ISourceBlock<T>, target: ITargetBlock<T>, options?: ILinkOptions<T>) {
        this._source = source;
        this._target = target;
        this._options = options;

        this._addedObserver = source.addedObservable.add(this.forwardAdded.bind(this));
        this._removedObserver = source.removedObservable.add(this.forwardRemoved.bind(this));
        this._updatedObserver = source.updatedObservable.add(this.forwardUpdated.bind(this));
    }

    public get source(): ISourceBlock<T> {
        return this._source;
    }

    public get target(): ITargetBlock<T> {
        return this._target;
    }

    public get options(): ILinkOptions<T> | undefined {
        return this._options;
    }

    public dispose(): void {
        this._addedObserver?.disconnect();
        this._removedObserver?.disconnect();
        this._updatedObserver?.disconnect();
        this._addedObserver = null;
        this._removedObserver = null;
        this._updatedObserver = null;
    }

    public forwardAdded(eventData: IPipelineMessageType<T>, eventState: EventState): void {
        if (this._target && this._target.added) {
            const filter = this._options?.acceptAdded ?? this.options?.accept;
            eventData = filter ? this._filter(eventData, filter) : eventData;
            this._target.added(eventData, eventState);
        }
    }

    public forwardRemoved(eventData: IPipelineMessageType<T>, eventState: EventState): void {
        if (this._target && this._target.removed) {
            const filter = this._options?.acceptRemoved ?? this.options?.accept;
            eventData = filter ? this._filter(eventData, filter) : eventData;
            this._target.removed(eventData, eventState);
        }
    }

    public forwardUpdated(eventData: IPipelineMessageType<T>, eventState: EventState): void {
        if (this._target && this._target.updated) {
            const filter = this._options?.acceptUpdated ?? this.options?.accept;
            eventData = filter ? this._filter(eventData, filter) : eventData;
            this._target.updated(eventData, eventState);
        }
    }

    protected _filter(eventData: IPipelineMessageType<T>, filter: (data: T) => boolean): IPipelineMessageType<T> {
        const filtered = [];
        for (let i = 0; i != eventData.length; i++) {
            const d = eventData[i];
            if (filter(d)) {
                filtered.push(d);
            }
        }
        return filtered;
    }
}
