import { ICanvasRenderingContext } from "@babylonjs/core";
import { Container } from "@babylonjs/gui";
import { IGeo2 } from "core/geography/geography.interfaces";
import { ISize3 } from "core/geometry/geometry.interfaces";
import { ITile, ITileMapApi, ITileMetrics } from "core/tiles/tiles.interfaces";
import { TileContentManager } from "core/tiles/tiles.content.manager";
import { TileMapView, UpdateEventArgs } from "core/tiles/tiles.mapview";
export declare class MapControl extends Container implements ITileMapApi {
    _view: TileMapView<HTMLImageElement>;
    _activ: Map<string, ITile<HTMLImageElement>>;
    constructor(name: string, manager: TileContentManager<HTMLImageElement>, center?: IGeo2, lod?: number);
    hasTile(key: string): boolean;
    getTile(key: string): ITile<HTMLImageElement> | undefined;
    invalidateSize(w: number, h: number): ITileMapApi;
    setView(center: IGeo2, zoom?: number, rotation?: number): ITileMapApi;
    setZoom(zoom: number): ITileMapApi;
    setAzimuth(r: number): ITileMapApi;
    zoomIn(delta: number): ITileMapApi;
    zoomOut(delta: number): ITileMapApi;
    translate(tx: number, ty: number): ITileMapApi;
    rotate(r: number): ITileMapApi;
    getContext(options?: CanvasRenderingContext2DSettings | undefined): ICanvasRenderingContext;
    get resolution(): ISize3;
    get view(): TileMapView<HTMLImageElement>;
    get metrics(): ITileMetrics;
    get azimuth(): number;
    protected onUpdate(args: UpdateEventArgs<HTMLImageElement>): void;
    protected onUpdateTiles(args: UpdateEventArgs<HTMLImageElement>): void;
    protected onUpdateView(args: UpdateEventArgs<HTMLImageElement>): void;
}
