/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A valid 3D Tiles style expression. Details are described in the 3D Tiles Styling specification.
 */
export type Expression = string;
/**
 * 3D Tiles style expression that evaluates to a number. Details are described in the 3D Tiles Styling specification.
 */
export type NumberExpression = number | string;
/**
 * 3D Tiles style `expression` that evaluates to a Color. Details are described in the 3D Tiles Styling specification.
 */
export type ColorExpression = string;
/**
 * A boolean or string with a 3D Tiles style expression that evaluates to a boolean. Details are described in the 3D Tiles Styling specification.
 */
export type BooleanExpression = boolean | string;
