import { PropertyChangedEventArgs, Observable } from "../../events";
import { ITileNavigationState } from "./tiles.navigation.interfaces";
import { ValidableBase } from "../../types";
import { ITileMetrics } from "../tiles.interfaces";
import { ICartesian2 } from "../../geometry/";
import { IGeo2, Bearing } from "../../geography";
export declare class TileNavigationState extends ValidableBase implements ITileNavigationState {
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<ITileNavigationState, unknown>>;
    _stateChangedObservable?: Observable<ITileNavigationState>;
    _lodf: number;
    _center: IGeo2;
    _azimuth: Bearing;
    _cartesianCache: ICartesian2;
    constructor(metrics: ITileMetrics, center?: IGeo2, lod?: number, azimuth?: number);
    get lod(): number;
    get scale(): number;
    get center(): IGeo2;
    set center(center: IGeo2);
    get zoom(): number;
    set zoom(lodf: number);
    get azimuth(): Bearing;
    set azimuth(r: Bearing);
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<ITileNavigationState, unknown>>;
    get stateChangedObservable(): Observable<ITileNavigationState>;
    setView(center: IGeo2 | Array<number>, zoom?: number, rotation?: number): TileNavigationState;
    zoomIn(delta: number): TileNavigationState;
    zoomOut(delta: number): TileNavigationState;
    translatePixel(tx: number, ty: number, metrics?: ITileMetrics): TileNavigationState;
    translate(lat: IGeo2 | Array<number> | number, lon?: number): TileNavigationState;
    rotate(r: number): TileNavigationState;
    protected _doValidate(): void;
    private rotatePointInv;
}
