/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { IRootProperty } from "../common/rootProperty";
import { IBinaryBodyReference, GlobalPropertyBoolean, GlobalPropertyCartesian3, GlobalPropertyInteger } from "./featureTable";

/**
 * A set of Instanced 3D Model semantics that contains values defining the position and appearance properties for instanced models in a tile.
 */
export interface IInstanced3DModelFeatureTable extends IRootProperty {
    POSITION?: IBinaryBodyReference;
    POSITION_QUANTIZED?: IBinaryBodyReference;
    NORMAL_UP?: IBinaryBodyReference;
    NORMAL_RIGHT?: IBinaryBodyReference;
    NORMAL_UP_OCT32P?: IBinaryBodyReference;
    NORMAL_RIGHT_OCT32P?: IBinaryBodyReference;
    SCALE?: IBinaryBodyReference;
    SCALE_NON_UNIFORM?: IBinaryBodyReference;
    BATCH_ID?: IBinaryBodyReference;
    INSTANCES_LENGTH: GlobalPropertyInteger;
    RTC_CENTER?: GlobalPropertyCartesian3;
    QUANTIZED_VOLUME_OFFSET?: GlobalPropertyCartesian3;
    QUANTIZED_VOLUME_SCALE?: GlobalPropertyCartesian3;
    EAST_NORTH_UP?: GlobalPropertyBoolean;
}
