// Important Note: This file has been generated as part of the build process.
// Therefore, any manual changes made to this file will be overridden by the next build.
// We strongly advise against editing this file directly, as it may cause unintended consequences and affect the final product.
import { ShaderStore } from "@babylonjs/core";
const name = "dummy";
const shader = `#define WEBGL2 
#define SHADER_NAME vertex:webmap
precision highp float;uniform mat4 world;struct Plane {vec3 point;vec3 normal;};float clipDistance(vec4 worldPos,Plane plane ){vec3 p=worldPos.xyz-plane.point;return dot(p,plane.normal);}uniform Plane uNorthClip;uniform Plane uSouthClip;uniform Plane uEastClip;uniform Plane uWestClip;uniform Plane uTopClip;uniform Plane uBottomClip;out vec4 vfClipDistance;vec3 elevation_rgbaToNormal(vec4 rgba) {float x=(2.0*rgba.r)-1.0;float y=(2.0*rgba.g)-1.0;float z=(rgba.b*255.0-128.0)/127.0;return vec3(x,z,y);}uniform highp sampler2DArray uAltitudes;uniform highp sampler2DArray uNormals;uniform highp vec2 uAltRange;in vec4 demIds;uniform mat4 world;uniform mat4 viewProjection;in vec3 position;in vec2 uv;uniform vec3 uTerrainColor;void main(void) {mat4 finalWorld=world;float depth=demIds[int(position.z)];vec3 v=vec3(uv.xy,depth);if( depth<0.0) {v.x=v.x==0.0 ? 1.0 : v.x;v.y=v.y==0.0 ? 1.0 : v.y;v.z=demIds[0];}float alt0=float(texture(uAltitudes,v));float alt=(alt0-uAltRange.x);vec4 p=world*vec4(position.xy,alt ,1.0);vec3 worldpos=(world*p).xyz;vec4 pixel=texture(uNormals,v);n=vec4(elevation_rgbaToNormal(pixel),1.0);vec3 worldnormal=normalize((world*n).xyz);vfClipDistance.x=clipDistance(worldPos,uNorthClip);vfClipDistance.y=clipDistance(worldPos,uSouthClip);vfClipDistance.z=clipDistance(worldPos,uEastClip);vfClipDistance.w=clipDistance(worldPos,uWestClip);gl_Position=viewProjection*worldpos;}`;
ShaderStore.ShadersStore[name] = shader;
/** @internal */ export const dummy = { name, shader };