import { IDisplay, ITileMapLayer, ITileMapLayerView, ITileNavigationState, TileMapBase } from "core/tiles";
import { IElevationGridFactory, IElevationOptions, IMap3D, IMap3DMaterial, Map3DContentType } from "./map.interfaces";
import { Mesh, Scene, TransformNode } from "@babylonjs/core";
import { Nullable } from "core/types";
import { EventState, PropertyChangedEventArgs } from "core/events";
import { ICartesian3, ISize2 } from "core/geometry";
export declare class Map3D extends TileMapBase<Map3DContentType> implements IMap3D, IElevationOptions {
    static DefaultGridSize: number;
    static DefaultExageration: number;
    static TEMPLATE_SUFFIX: string;
    static MATERIAL_SUFFIX: string;
    _root: TransformNode;
    _gridSize: number | ISize2;
    _offset?: ICartesian3;
    _exageration?: number;
    _grid: Mesh;
    _material: IMap3DMaterial;
    constructor(root: TransformNode);
    get elevationOptions(): IElevationOptions;
    get material(): IMap3DMaterial;
    get grid(): Mesh;
    get name(): string;
    get root(): TransformNode;
    get gridSize(): number | ISize2;
    set gridSize(value: number | ISize2);
    get offset(): ICartesian3 | undefined;
    set offset(value: ICartesian3 | undefined);
    get exageration(): number | undefined;
    set exageration(value: number | undefined);
    protected _buildLayerView(layer: ITileMapLayer<Map3DContentType>): Nullable<ITileMapLayerView<any>>;
    protected _onNavigationPropertyChanged(event: PropertyChangedEventArgs<ITileNavigationState, unknown>, state: EventState): void;
    protected _rotateMap(nav: Nullable<ITileNavigationState>): void;
    protected _onNavigationBinded(nav: Nullable<ITileNavigationState>): void;
    protected _onDisplayBinded(display: Nullable<IDisplay>): void;
    private _bindDisplayInternal;
    protected _onLayerViewAdded(eventData: Array<ITileMapLayerView<Map3DContentType>>, eventState: EventState): void;
    protected _onLayerViewRemoved(eventData: Array<ITileMapLayerView<Map3DContentType>>, eventState: EventState): void;
    protected _buildQualifiedName(n: string): string;
    protected _buildTemplateName(): string;
    protected _buildMaterialName(): string;
    protected _buildMaterial(name: string, scene?: Scene): IMap3DMaterial;
    protected _buildTemplate(scene?: Scene): Mesh;
    protected _buildMesh(name: string, scene?: Scene): Mesh;
    protected _buildGridFactory(): IElevationGridFactory;
    private _buildGridFactoryInternal;
}
