import { IDemInfos } from "core/dem";
import { IDisplay, ITileNavigationState, ITileView, TileMapLayerView } from "core/tiles";
import { IElevationHost, IElevationLayer } from "./map.elevation.interfaces";
import { ElevationGridFactory } from "./map.elevation.host.factory";
import { AbstractMesh, Material, Mesh, Scene, TransformNode } from "@babylonjs/core";
import { ElevationTile, IElevationTile } from "./map.elevation.mesh";
import { ICartesian2 } from "core/geometry";
import { Nullable } from "core/types";
import { EventState, PropertyChangedEventArgs } from "core/events";
import { Bearing } from "core/geography";
export declare class ElevationHost extends TileMapLayerView<IDemInfos> implements IElevationHost {
    static TemplateNameSuffix: string;
    static RootNameSuffix: string;
    static MaterialNameSuffix: string;
    _grid: Mesh;
    _tilesRoot: TransformNode;
    _cartesianCenterCache: Nullable<ICartesian2>;
    constructor(layer: IElevationLayer, display: Nullable<IDisplay>, navigation: Nullable<ITileNavigationState>, source: ITileView, scene?: Scene);
    get tilesRoot(): TransformNode;
    protected get isReady(): boolean;
    protected _buildRoot(scene?: Scene): TransformNode;
    protected _applyExageration(exageration: number, scale?: number): void;
    protected _applyNavigation(nav: Nullable<ITileNavigationState>): void;
    protected _applyPosition(x: number, y: number, z: number): void;
    protected _onLayerPropertyChanged(eventData: PropertyChangedEventArgs<unknown, unknown>, eventState: EventState): void;
    protected _onNavigationChanged(oldValue: Nullable<ITileNavigationState>, newValue: Nullable<ITileNavigationState>): void;
    protected _onNavigationPropertyChanged(event: PropertyChangedEventArgs<ITileNavigationState, unknown>, state: EventState): void;
    get exageration(): number;
    protected _onZoomChanged(scale: number, exageration?: number): void;
    protected _onAzimuthChanged(azimuth: Bearing): void;
    protected _onCenterChanged(center: Nullable<ICartesian2>): void;
    protected _buildTemplate(scene?: Scene): Mesh;
    protected _buildMesh(name: string, scene?: Scene): Mesh;
    protected _buildMaterial(name: string, scene?: Scene): Material;
    protected _buildGridFactory(): ElevationGridFactory;
    protected _buildQualifiedName(n: string): string;
    protected _buildTemplateName(): string;
    protected _buildMaterialName(): string;
    protected _buildRootName(): string;
    private _buildGridFactoryInternal;
    protected _onTilesAdded(tiles: ElevationTile | Array<ElevationTile>): void;
    protected _onTilesRemoved(tiles: ElevationTile | Array<ElevationTile>): void;
    protected _onTilesUpdated(tiles: ElevationTile | Array<ElevationTile>): void;
    protected _onTileAdded(tile: ElevationTile): void;
    protected _onTileRemoved(tile: ElevationTile): void;
    protected _onTileUpdated(tile: ElevationTile): void;
    protected _createInstance(tile: ElevationTile): AbstractMesh;
    protected _setActivTilePositions(center: ICartesian2): void;
    protected _setTilePosition(tile: IElevationTile, center: ICartesian2): void;
}
