import { AbstractMesh, Mesh, Nullable, Scene, TransformNode, VertexData, Material } from "@babylonjs/core";
import { TerrainGridOptions, TerrainGridOptionsBuilder } from "core/meshes";
import { IHasActivTiles, IHasNavigationState, ILinkOptions, IPipelineMessageType, ITargetBlock, ITile, ITileCollection, ITileMapLayer, ITileMapLayerContainer, ITileMetrics, ITileMetricsProvider, ITileNavigationState, ITilePipelineLink, ITransformBlock } from "core/tiles";
import { ICartesian2, ICartesian3 } from "core/geometry";
import { PropertyChangedEventArgs, EventState, Observable, Observer } from "core/events";
import { Bearing } from "core/geography";
import { IElevationMesh, IElevationTile } from "./map.elevation.tile";
import { IElevationLayerOptions } from "./map.elevation.layer";
import { IDemInfos } from "core/dem";
import { Map3dTextureContentType } from "./map.elevation";
import { Map3dScaleController } from "./map.scale.controller";
import { HolographicDisplay } from "../display";
export declare class Map3dElevationHost extends TransformNode implements ITransformBlock<ITile<IDemInfos>, ITile<IElevationMesh>>, IHasActivTiles<IElevationMesh>, ITileMetricsProvider, IHasNavigationState {
    static DefaultName: string;
    static TileRootSuffix: string;
    private static InitZ;
    private static InitUV;
    _updatedObservable?: Observable<IPipelineMessageType<ITile<IElevationMesh>>>;
    _addedObservable?: Observable<IPipelineMessageType<ITile<IElevationMesh>>>;
    _removedObservable?: Observable<IPipelineMessageType<ITile<IElevationMesh>>>;
    _links: Array<ITilePipelineLink<ITile<IElevationMesh>>>;
    _textureLayers: ITileMapLayerContainer<Map3dTextureContentType, ITileMapLayer<Map3dTextureContentType>>;
    _elevationSource: ITileMapLayer<IDemInfos>;
    _grid: VertexData;
    _template: Mesh;
    _scaleController: Nullable<Map3dScaleController>;
    _scaleObserver: Nullable<Observer<ICartesian3>>;
    _exageration?: number;
    _insets?: ICartesian3;
    _gridOptions?: TerrainGridOptions | TerrainGridOptionsBuilder;
    _activTiles: ITileCollection<IElevationMesh>;
    _tilesRoot: TransformNode;
    _cartesianCenter: Nullable<ICartesian2>;
    constructor(name: string, layers: ITileMapLayerContainer<Map3dTextureContentType, ITileMapLayer<Map3dTextureContentType>>, source: ITileMapLayer<IDemInfos>, options?: IElevationLayerOptions, enabled?: boolean);
    get navigation(): ITileNavigationState;
    get metrics(): ITileMetrics;
    get activTiles(): ITileCollection<IElevationMesh>;
    added(eventData: IPipelineMessageType<ITile<IDemInfos>>, eventState: EventState): void;
    removed(eventData: IPipelineMessageType<ITile<IDemInfos>>, eventState: EventState): void;
    updated(eventData: IPipelineMessageType<ITile<IDemInfos>>, eventState: EventState): void;
    get updatedObservable(): Observable<IPipelineMessageType<ITile<IElevationMesh>>>;
    get addedObservable(): Observable<IPipelineMessageType<ITile<IElevationMesh>>>;
    get removedObservable(): Observable<IPipelineMessageType<ITile<IElevationMesh>>>;
    linkTo(target: ITargetBlock<ITile<IElevationMesh>>, options?: ILinkOptions): void;
    unlinkFrom(target: ITargetBlock<ITile<IElevationMesh>>): ITilePipelineLink<ITile<IElevationMesh>> | undefined;
    get mesh(): Mesh;
    bindDisplay(display?: HolographicDisplay): void;
    protected _onScaleChanged(scale: ICartesian3): void;
    protected _buildMesh(material?: Nullable<Material>, scene?: Scene): Mesh;
    protected _createMesh(name: string, scene?: Nullable<Scene>): Mesh;
    protected _buildInstance(name: string, tile: ITile<IElevationMesh>): AbstractMesh;
    protected _onNavigationPropertyChanged(event: PropertyChangedEventArgs<ITileNavigationState, unknown>, state: EventState): void;
    protected _onZoomChanged(scale: number): void;
    protected _onAzimuthChanged(azimuth: Bearing): void;
    protected _onCenterChanged(center: Nullable<ICartesian2>): void;
    protected _setTilePosition(tile: ITile<IElevationMesh>, center: ICartesian2): void;
    protected _buildTopology(): VertexData;
    protected _buildTerrainOptions(options?: TerrainGridOptions | TerrainGridOptionsBuilder): TerrainGridOptions;
    protected _onTileAdded(tile: ITile<IDemInfos>, eventState: EventState): void;
    protected _createElevationTile(tile: ITile<IDemInfos>): IElevationTile;
    protected _onTileRemoved(tile: ITile<IDemInfos>, eventState: EventState): void;
    protected _onTileUpdated(tile: ITile<IDemInfos>, eventState: EventState): void;
    protected _buildNameWithSuffix(suffix: string): string;
    protected _createDefaultMaterial(scene?: Scene): Material;
}
