import { IDemInfos } from "core/dem";
import { ITile, ITileDisplay, ITileMap, ITileMapLayer, ITileMetrics, ITileNavigationApi, ITileNavigationState, ImageLayer } from "core/tiles";
import { ElevationLayer, ElevationTile } from "./map.elevation.layer";
import { EventState, Observable } from "core/events";
import { Nullable, TransformNode } from "@babylonjs/core";
import { IGeo2 } from "core/geography";
export type ElevationTileContentType = IDemInfos | HTMLImageElement;
export declare class ElevationMap extends TransformNode implements ITileNavigationApi<ElevationMap>, ITileMap<ElevationTileContentType, ITileMapLayer<ElevationTileContentType>> {
    private _map;
    constructor(name: string, display?: ITileDisplay);
    setViewMap(center: IGeo2 | Array<number>, zoom?: number, rotation?: number): ElevationMap;
    zoomMap(delta: number): ElevationMap;
    zoomInMap(delta: number): ElevationMap;
    zoomOutMap(delta: number): ElevationMap;
    translatePixelMap(tx: number, ty: number, metrics?: ITileMetrics): ElevationMap;
    translateMap(lat: IGeo2 | Array<number> | number, lon?: number): ElevationMap;
    rotateMap(r: number): ElevationMap;
    get navigation(): ITileNavigationState;
    get layerAddedObservable(): Observable<ITileMapLayer<ElevationTileContentType>>;
    get layerRemovedObservable(): Observable<ITileMapLayer<ElevationTileContentType>>;
    getLayers(predicate?: (l: ITileMapLayer<ElevationTileContentType>) => boolean, sorted?: boolean): IterableIterator<ITileMapLayer<ElevationTileContentType>>;
    addLayer(layer: ITileMapLayer<ElevationTileContentType>): void;
    removeLayer(layer: ITileMapLayer<ElevationTileContentType>): void;
    dispose(): void;
    get display(): Nullable<ITileDisplay>;
    added(eventData: Array<ElevationTile> | Array<ITile<HTMLImageElement>>, eventState: EventState): void;
    removed(eventData: Array<ElevationTile> | Array<ITile<HTMLImageElement>>, eventState: EventState): void;
    updated(eventData: Array<ElevationTile> | Array<ITile<HTMLImageElement>>, eventState: EventState): void;
    protected _onElevationLayerAdded(layer: ElevationLayer): void;
    protected _onElevationLayerRemoved(layer: ElevationLayer): void;
    protected _onTextureLayerAdded(layer: ImageLayer): void;
    protected _onTextureLayerRemoved(layer: ImageLayer): void;
    protected _onElevationAdded(tile: ElevationTile): void;
    protected _onElevationRemoved(tile: ElevationTile): void;
    protected _onElevationUpdated(tile: ElevationTile): void;
    protected _onTextureAdded(tile: ITile<HTMLImageElement>): void;
    protected _onTextureRemoved(tile: ITile<HTMLImageElement>): void;
    protected _onTextureUpdated(tile: ITile<HTMLImageElement>): void;
}
