import { IDemInfos } from "core/dem";
import { ITile, ITileDisplay, ITileMap, ITileMapLayer, ITileMetrics, ITileNavigationState, ImageLayer } from "core/tiles";
import { ElevationLayer, ElevationTile } from "./map.elevation.layer";
import { EventState, Observable } from "core/events";
import { Nullable, TransformNode } from "@babylonjs/core";
import { IGeo2 } from "core/geography";
import { Map3dMaterial } from "../materials";
export type Map3dTileContentType = IDemInfos | HTMLImageElement;
export declare class Map3d extends TransformNode implements ITileMap<Map3dTileContentType, ITileMapLayer<Map3dTileContentType>, Map3d> {
    private _map;
    private _material;
    constructor(name: string, display?: ITileDisplay, material?: Nullable<Map3dMaterial>);
    setViewMap(center: IGeo2 | Array<number>, zoom?: number, rotation?: number): Map3d;
    zoomMap(delta: number): Map3d;
    zoomInMap(delta: number): Map3d;
    zoomOutMap(delta: number): Map3d;
    translateUnitsMap(tx: number, ty: number, metrics?: ITileMetrics): Map3d;
    translateMap(lat: IGeo2 | Array<number> | number, lon?: number): Map3d;
    rotateMap(r: number): Map3d;
    get navigation(): ITileNavigationState;
    get layerAddedObservable(): Observable<ITileMapLayer<Map3dTileContentType>>;
    get layerRemovedObservable(): Observable<ITileMapLayer<Map3dTileContentType>>;
    getLayers(predicate?: (l: ITileMapLayer<Map3dTileContentType>) => boolean, sorted?: boolean): IterableIterator<ITileMapLayer<Map3dTileContentType>>;
    addLayer(layer: ITileMapLayer<Map3dTileContentType>): void;
    removeLayer(layer: ITileMapLayer<Map3dTileContentType>): void;
    dispose(): void;
    get display(): Nullable<ITileDisplay>;
    added(eventData: Array<ElevationTile> | Array<ITile<HTMLImageElement>>, eventState: EventState): void;
    removed(eventData: Array<ElevationTile> | Array<ITile<HTMLImageElement>>, eventState: EventState): void;
    updated(eventData: Array<ElevationTile> | Array<ITile<HTMLImageElement>>, eventState: EventState): void;
    protected _onElevationLayerAdded(layer: ElevationLayer): void;
    protected _onElevationLayerRemoved(layer: ElevationLayer): void;
    protected _onTextureLayerAdded(layer: ImageLayer): void;
    protected _onTextureLayerRemoved(layer: ImageLayer): void;
    protected _onElevationAdded(tile: ElevationTile): void;
    protected _onElevationRemoved(tile: ElevationTile): void;
    protected _onElevationUpdated(tile: ElevationTile): void;
    protected _onTextureAdded(tile: ITile<HTMLImageElement>): void;
    protected _onTextureRemoved(tile: ITile<HTMLImageElement>): void;
    protected _onTextureUpdated(tile: ITile<HTMLImageElement>): void;
}
