export declare class Ellipsoid {
    static readonly WGS84: Ellipsoid;
    static readonly GRS80: Ellipsoid;
    static readonly GRS67: Ellipsoid;
    static readonly ANS: Ellipsoid;
    static readonly WGS72: Ellipsoid;
    static readonly Clarke1858: Ellipsoid;
    static readonly Clarke1880: Ellipsoid;
    static FromAAndInverseF(name: string, semiMajor: number, inverseFlattening: number): Ellipsoid;
    static FromAAndF(name: string, semiMajor: number, flattening: number): Ellipsoid;
    _name: string;
    _a: number;
    _b: number;
    _aa: number;
    _bb: number;
    _f: number;
    _p1mf: number;
    _invf: number;
    _c: number;
    _e: number;
    _ee: number;
    _invaa: number;
    _aadc: number;
    _bbdcc: number;
    _l: number;
    _p1mee: number;
    _p1meedaa: number;
    _hmin: number;
    _ll4: number;
    _ll: number;
    private constructor();
    get Name(): string;
    get SemiMajorAxis(): number;
    get SemiMinorAxis(): number;
    get Flattening(): number;
    get InverseFlattening(): number;
    get LinearEccentricity(): number;
    get Eccentricity(): number;
    get SqrEccentricity(): number;
    get SemiLatusRectum(): number;
    IsEquals(other: Ellipsoid): boolean;
    clone(name: string, scale?: number): Ellipsoid;
}
