import { IGeo2 } from "./geography.interfaces";
import { Geo2 } from "./geography.position";
export declare class KnownPlaces {
    static FillSelectElement(select: HTMLSelectElement, places: any, callback: (name: string, geo: IGeo2) => void): HTMLSelectElement;
    static Mountains: {
        Everest: Geo2;
        K2: Geo2;
        Kangchenjunga: Geo2;
        Lhotse: Geo2;
        Makalu: Geo2;
        ChoOyu: Geo2;
        Dhaulagiri: Geo2;
        Manaslu: Geo2;
        NangaParbat: Geo2;
        Annapurna: Geo2;
        Matterhorn: Geo2;
        MontBlanc: Geo2;
        Denali: Geo2;
        Aconcagua: Geo2;
        Kilimanjaro: Geo2;
        Elbrus: Geo2;
        PuncakJaya: Geo2;
    };
    static Volcanoes: {
        Krakatoa: Geo2;
        Vesuvius: Geo2;
        Etna: Geo2;
        MaunaLoa: Geo2;
        Kilauea: Geo2;
        Fuji: Geo2;
        StHelens: Geo2;
        Pinatubo: Geo2;
        Rainier: Geo2;
        Cotopaxi: Geo2;
        Popocatepetl: Geo2;
        Eyjafjallajokull: Geo2;
        Santorini: Geo2;
        Kilimanjaro: Geo2;
        Arenal: Geo2;
        Yellowstone: Geo2;
        Tambora: Geo2;
        Sakurajima: Geo2;
    };
    static SightsAndParks: {
        GrandCanyon: Geo2;
        Yellowstone: Geo2;
        GreatBarrierReef: Geo2;
        Yosemite: Geo2;
        Serengeti: Geo2;
        MachuPicchu: Geo2;
        Banff: Geo2;
        Galapagos: Geo2;
        TorresDelPaine: Geo2;
        PlitviceLakes: Geo2;
        VictoriaFalls: Geo2;
        Santorini: Geo2;
        Petra: Geo2;
        IguazuFalls: Geo2;
        Kruger: Geo2;
        BryceCanyon: Geo2;
        CliffsOfMoher: Geo2;
        AngkorWat: Geo2;
        HaLongBay: Geo2;
    };
}
