import { IEnvelope, IGeo3, ISize3 } from "./geography.interfaces";
export declare class Envelope implements IEnvelope {
    static MaxLongitude: number;
    static MaxLatitude: number;
    static MinLongitude: number;
    static MinLatitude: number;
    static FromSize(position: IGeo3, size: ISize3): Envelope;
    static FromPoints(a: IGeo3, b: IGeo3): Envelope;
    _min: IGeo3;
    _max: IGeo3;
    private constructor();
    get north(): number;
    get south(): number;
    get east(): number;
    get west(): number;
    get bottom(): number | undefined;
    get top(): number | undefined;
    get nw(): IGeo3;
    get sw(): IGeo3;
    get ne(): IGeo3;
    get se(): IGeo3;
    equals(other: IEnvelope): boolean;
    clone(): IEnvelope;
    get hasAltitude(): boolean;
    get center(): IGeo3;
    get size(): ISize3;
    add(lat: number | IGeo3, lon?: number, alt?: number): IEnvelope;
    addInPlace(lat: number | IGeo3, lon?: number, alt?: number): IEnvelope;
    intersectWith(bounds: IEnvelope): boolean;
    contains(loc: IGeo3): boolean;
    containsFloat(lat: number, lon?: number, alt?: number): boolean;
}
