import { ICartesian2 } from "../geometry/geometry.interfaces";
import { EventArgs } from "../events/events.args";
import { Observable } from "../events/events.observable";
import { IDisposable, Nullable } from "../types";
import { ITile, ITileAddress, ITileBuilder, ITileMetricsProvider, TileContent } from "./tiles.interfaces";
import { ITileMapApi } from "./tiles.interfaces.api";

export interface IPipelineComponent extends IDisposable {
    id?: string;
}

export interface IContextMetrics {
    lod: number;
    scale: number;
    center: ICartesian2;
}

/// <summary>
/// Base class of event args carrying a tile address and a value.
/// </summary>
export class AddressValueEventArgs<S, T> extends EventArgs<S> {
    _address: ITileAddress;
    _value: T;

    public constructor(sender: S, address: ITileAddress, value: T) {
        super(sender);
        this._address = address;
        this._value = value;
    }

    public get address(): ITileAddress {
        return this._address;
    }

    public get value(): T {
        return this._value;
    }
}

/// <summary>
/// Event args carrying a tile address and a content. This is used by the content provider observable.
/// </summary>
export class ContentUpdateEventArgs<T> extends AddressValueEventArgs<ITileContentProvider<T>, TileContent<T>> {
    private _result: number;

    public constructor(sender: ITileContentProvider<T>, address: ITileAddress, content: TileContent<T>, result: number = 0) {
        super(sender, address, content);
        this._result = result;
    }

    public get content(): TileContent<T> {
        return this.value;
    }

    /// <summary>
    /// Result of the content update. 0 means success, any other value is an error code.
    /// </summary>
    public get result(): number {
        return this._result;
    }
}

/// <summary>
/// The TileContentProvider is responsible for fetching the content of tiles. It is tasked with the following:
/// - Accepting Tile Addresses: The TileContentProvider is responsible for accepting or rejecting tile addresses based on the metrics of the View.
/// - Fetching Tile Content: Once a tile address is accepted, the TileContentProvider is tasked with fetching the content of the tile.
/// - Managing Content Update Events: The TileContentProvider is responsible for managing events related to content updates. It uses the observable pattern
///   to send notifications about content updates, allowing other components of the system to react and update accordingly.
/// </summary>
export interface ITileContentProvider<T> extends ITileMetricsProvider, IPipelineComponent {
    contentUpdateObservable: Observable<ContentUpdateEventArgs<T>>;

    accept(address: ITileAddress): boolean;

    getTileContent(address: ITileAddress): Nullable<TileContent<T>>;
}

/// <summary>
/// The View component is tasked with selecting appropriate tile addresses, guided by the Tile Metrics and navigation properties. Its role is expanded to include the following:
/// - Tile Selection Based on Navigation Properties: Considers the geographic center, azimuth, and level of detail in tile selection, ensuring relevance and accuracy.
/// - Dimension and Scalability: Defines the dimension in unitless TileXY units, enabling flexibility and adaptability to different screen sizes and resolutions.
/// - Event Management Through Observable Pattern: Crucially, the View is responsible for managing events using the observable pattern. It sends notifications about 'Added'
///   and 'Removed' TileAddresses, allowing other components of the system to react and update accordingly. This feature is vital for ensuring that the system remains dynamic
///   and responsive to changes, such as user navigation or zoom adjustments.
/// </summary>
export interface ITileView extends IPipelineComponent {
    addressAddedObservable: Observable<Array<ITileAddress>>;
    addressRemovedObservable: Observable<Array<ITileAddress>>;
    api: Nullable<ITileMapApi>;
}

/// <summary>
/// The TileProvider acts as a critical intermediary between the View and the TileContentProvider. Its responsibilities include:
/// - Observing View Events: The TileProvider is tasked with observing events generated by the View, particularly those related to tile addition or removal.
/// - Synchronization with TileContentProvider: Upon receiving events from the View, the TileProvider synchronizes these with the TileContentProvider.
///   This synchronization ensures that the content of the tiles is in line with the changes in the View.
/// - Managing Tile Events: Once the TileContent is ready, the TileProvider takes over the role of event management. It uses the observable pattern
///   to handle 'Add', 'Remove', and 'Update' tile events. The 'Update' event is particularly significant in the context of asynchronous content loading,
///   allowing the system to dynamically update tiles as new content becomes available or as user interactions necessitate changes.
/// </summary>
export interface ITileProvider<T> extends IPipelineComponent {
    /// <summary> messaged when a tile is updated </summary>
    tileUpdatedObservable: Observable<Array<ITile<T>>>;

    /// <summary> messaged when a tile is added </summary>
    tileAddedObservable: Observable<Array<ITile<T>>>;

    /// <summary> messaged when a tile is removed </summary>
    tileRemovedObservable: Observable<Array<ITile<T>>>;

    /// <summary>
    /// Get tiles using one address. Typically used by the pipeline, this method is using the underlying providers,
    /// first to verify if the content provider are accepting the address, and then ask for the contents itself.
    /// </summary>
    getTile(address: ITileAddress): Nullable<ITile<T>[]>;

    /// <summary> register a content provider to the pipeline </summary>
    addContentProvider<P extends T>(contentProvider: ITileContentProvider<P>, builder: ITileBuilder<P>): void;

    /// <summary> unregister a content provider from the pipeline </summary>
    removeContentProvider<P extends T>(name: string): void;

    /// <summary> get a content provider from the pipeline using is name. Name is usually comming from ITile.namespace. </summary>
    getProviderByName<P extends T>(name: string): ITileContentProvider<P> | undefined;
}

export interface ITileConsumer<T> extends IPipelineComponent {}
