import { PropertyChangedEventArgs } from "../../events/events.args";
import { Observable, Observer } from "../../events/events.observable";
import { IEnvelope, IGeo2 } from "../../geography/geography.interfaces";
import { ICartesian2, IRectangle, ISize2 } from "../../geometry/geometry.interfaces";
import { ITileMetrics } from "../tiles.interfaces";
import { ITileMapApi } from "./tiles.interfaces.api";
import { IValidable } from "../../types";
import { GeoBounded } from "../../geography/geography.envelope";
export declare class TileMapApiBase extends GeoBounded implements ITileMapApi, IValidable<TileMapApiBase> {
    static ClampAzimuth(a: number): number;
    _resizeObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, ISize2>>;
    _centerObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, IGeo2>>;
    _zoomObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    _azimuthObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    _viewChangedObservable?: Observable<ITileMapApi>;
    _metrics: ITileMetrics;
    _w: number;
    _h: number;
    _lodf: number;
    _lod: number;
    _bounds?: IEnvelope;
    _center: IGeo2;
    _azimuth: number;
    _cosangle: number;
    _sinangle: number;
    _valid: boolean;
    _cartesianCache: ICartesian2;
    _centerXY: ICartesian2;
    _scale: number;
    _boundsXY: IRectangle;
    constructor(metrics: ITileMetrics, size?: ISize2, center?: IGeo2, lod?: number, azimuth?: number);
    get isValid(): boolean;
    invalidate(): TileMapApiBase;
    validate(): TileMapApiBase;
    revalidate(): TileMapApiBase;
    get center(): IGeo2;
    get zoom(): number;
    get levelOfDetail(): number;
    get azimuth(): number;
    get scale(): number;
    get centerXY(): ICartesian2;
    get boundsXY(): IRectangle;
    get width(): number;
    get height(): number;
    get metrics(): ITileMetrics;
    get resizeObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, ISize2>>;
    get centerObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, IGeo2>>;
    get zoomObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    get azimuthObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    get viewChangedObservable(): Observable<ITileMapApi>;
    invalidateSize(w: number, h: number): ITileMapApi;
    setView(center: IGeo2, zoom?: number | undefined, azimuth?: number | undefined): ITileMapApi;
    setZoom(zoom: number): ITileMapApi;
    setAzimuth(r: number): ITileMapApi;
    zoomIn(delta: number): ITileMapApi;
    zoomOut(delta: number): ITileMapApi;
    translate(tx: number, ty: number): ITileMapApi;
    rotate(r: number): ITileMapApi;
    protected _doValidateInternal(): void;
    protected _beforeValidate(): void;
    protected _doValidate(): void;
    protected _afterValidate(): void;
    protected _buildEnvelope(): IEnvelope | undefined;
    protected _onResizeObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, ISize2>>): void;
    protected _onZoomObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, number>>): void;
    protected _onCenterObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, IGeo2>>): void;
    protected _onAzimuthObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, number>>): void;
    protected _onViewChangedObserverAdded(observer: Observer<ITileMapApi>): void;
    private _rotatePointInv;
    private _rotatePointsArround;
    private _rotatePointArround;
    protected _getRectangle(center: ICartesian2, scale: number): IRectangle;
}
