import { TileMapView, UpdateEventArgs } from "../tiles/tiles.mapview";
import { ITile, ITileMapApi, ITileMetrics, ITileMetricsProvider } from "../tiles/tiles.interfaces";
import { IGeo2 } from "../geography/geography.interfaces";
import { ICartesian2, ISize3 } from "../geometry/geometry.interfaces";
import { Observable, Observer } from "../events/events.observable";
import { TileContentProvider } from "core/tiles/tiles.content.provider";
export interface IMapDisplay {
    resolution: ISize3;
}
export declare abstract class AbstractDisplayMap<V, T extends ITile<V>, D extends IMapDisplay> implements ITileMetricsProvider, ITileMapApi {
    _display: D;
    _view: TileMapView<V>;
    _activ: Map<string, T>;
    _lod: number;
    _scale: number;
    _center: ICartesian2;
    _addedObservable?: Observable<T>;
    _removedObservable?: Observable<T>;
    _updatedObservable?: Observable<T>;
    constructor(display: D, manager: TileContentProvider<V>, center?: IGeo2, lod?: number);
    get addedObservable(): Observable<T>;
    get removedObservable(): Observable<T>;
    get updatedObservable(): Observable<T>;
    hasTile(key: string): boolean;
    getTile(key: string): T | undefined;
    invalidateSize(w: number, h: number): ITileMapApi;
    setView(center: IGeo2, zoom?: number, rotation?: number): ITileMapApi;
    setZoom(zoom: number): ITileMapApi;
    setAzimuth(r: number): ITileMapApi;
    zoomIn(delta: number): ITileMapApi;
    zoomOut(delta: number): ITileMapApi;
    translate(tx: number, ty: number): ITileMapApi;
    rotate(r: number): ITileMapApi;
    get display(): D;
    get view(): TileMapView<V>;
    get metrics(): ITileMetrics;
    get azimuth(): number;
    protected onUpdate(args: UpdateEventArgs<V>): void;
    protected onUpdateTiles(args: UpdateEventArgs<V>): void;
    protected onUpdateView(args: UpdateEventArgs<V>): void;
    notifyRemovedObserver(tile: T): void;
    notifyUpdatedObserver(tile: T): void;
    notifyAddedObserver(tile: T): void;
    private processRemoved;
    private processAdded;
    protected buildMapTile(t: ITile<V>): T;
    protected onAddedObserverAdded(observer: Observer<T>): void;
    protected onRemovedObserverAdded(observer: Observer<T>): void;
    protected onUpdatedObserverAdded(observer: Observer<T>): void;
    protected abstract onDeleted(key: string, tile: T): void;
    protected abstract onAdded(key: string, tile: T): void;
    protected abstract onUpdated(key: string, tile: T): void;
    protected abstract invalidateDisplay(): void;
    protected abstract invalidateTiles(added: Array<T> | undefined, removed: Array<ITile<V>> | undefined): void;
}
