import { PropertyChangedEventArgs } from "../events/events.args";
import { Observable, Observer } from "../events/events.observable";
import { IEnvelope, IGeo2 } from "../geography/geography.interfaces";
import { ICartesian2, ISize2 } from "../geometry/geometry.interfaces";
import { ITileMetrics } from "./tiles.interfaces";
import { ITileMapApi } from "./tiles.interfaces.api";
import { IValidable } from "../types";
import { GeoBounded } from "../geography/geography.envelope";
import { IContextMetrics } from "./tiles.interfaces.pipeline";
export declare class TileMapContextMetrics implements IContextMetrics {
    _lod: number;
    _scale: number;
    _center: ICartesian2;
    constructor(lod?: number, scale?: number, center?: ICartesian2);
    get lod(): number;
    get scale(): number;
    get center(): ICartesian2;
    clone(): TileMapContextMetrics;
}
export declare class TileMapBase extends GeoBounded implements ITileMapApi, IValidable<TileMapBase> {
    static ClampAzimuth(a: number): number;
    _resizeObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, ISize2>>;
    _centerObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, IGeo2>>;
    _zoomObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    _azimuthObservable?: Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    _metrics: ITileMetrics;
    _w: number;
    _h: number;
    _lodf: number;
    _lod: number;
    _bounds?: IEnvelope;
    _center: IGeo2;
    _azimuth: number;
    _cosangle: number;
    _sinangle: number;
    _context: TileMapContextMetrics;
    _valid: boolean;
    _cartesianCache: ICartesian2;
    constructor(metrics: ITileMetrics, size?: ISize2, center?: IGeo2, lod?: number, azimuth?: number);
    get width(): number;
    get height(): number;
    get metrics(): ITileMetrics;
    get isValid(): boolean;
    invalidate(): TileMapBase;
    validate(): TileMapBase;
    revalidate(): TileMapBase;
    get resizeObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, ISize2>>;
    get centerObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, IGeo2>>;
    get zoomObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    get azimuthObservable(): Observable<PropertyChangedEventArgs<ITileMapApi, number>>;
    invalidateSize(w: number, h: number): ITileMapApi;
    setView(center: IGeo2, zoom?: number | undefined, azimuth?: number | undefined): ITileMapApi;
    setZoom(zoom: number): ITileMapApi;
    setAzimuth(r: number): ITileMapApi;
    zoomIn(delta: number): ITileMapApi;
    zoomOut(delta: number): ITileMapApi;
    translate(tx: number, ty: number): ITileMapApi;
    rotate(r: number): ITileMapApi;
    protected _doValidate(): void;
    protected _buildEnvelope(): IEnvelope | undefined;
    protected _onResizeObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, ISize2>>): void;
    protected _onZoomObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, number>>): void;
    protected _onCenterObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, IGeo2>>): void;
    protected _onAzimuthObserverAdded(observer: Observer<PropertyChangedEventArgs<ITileMapApi, number>>): void;
    private _rotatePointInv;
    private _rotatePointsArround;
    private _rotatePointArround;
    private _getRectangle;
}
