import { ICartesian2 } from "../geometry/geometry.interfaces";
import { IGeo2 } from "../geography/geography.interfaces";
import { ITileMetrics, CellCoordinateReference } from "./tiles.interfaces";
import { TileSystemBounds } from "./tiles.system";
export declare abstract class AbstractTileMetrics extends TileSystemBounds implements ITileMetrics {
    static DefaultTileSize: number;
    static DefaultCellSize: number;
    static DefaultCoordinateReference: CellCoordinateReference;
    static DefaultOverlap: number;
    _tileSize: number;
    _cellSize: number;
    _cellCoordinateReference: CellCoordinateReference;
    _overlap: number;
    constructor(options?: Partial<ITileMetrics>);
    mapSize(levelOfDetail: number): number;
    get tileSize(): number;
    set tileSize(v: number);
    get cellSize(): number;
    set cellSize(v: number);
    get cellCoordinateReference(): CellCoordinateReference;
    set cellCoordinateReference(v: CellCoordinateReference);
    get overlap(): number;
    set overlap(v: number);
    mapScale(latitude: number, levelOfDetail: number, pixelPerUnit: number): number;
    abstract groundResolution(latitude: number, levelOfDetail: number): number;
    getLatLonToTileXY(latitude: number, longitude: number, levelOfDetail: number): ICartesian2;
    getTileXYToLatLon(x: number, y: number, levelOfDetail: number): IGeo2;
    getLatLonToPixelXY(latitude: number, longitude: number, levelOfDetail: number): ICartesian2;
    getPixelXYToLatLon(x: number, y: number, levelOfDetail: number): IGeo2;
    getTileXYToPixelXY(x: number, y: number): ICartesian2;
    getPixelXYToTileXY(x: number, y: number): ICartesian2;
    abstract getLatLonToTileXYToRef(latitude: number, longitude: number, levelOfDetail: number, tileXY?: ICartesian2 | undefined): void;
    abstract getTileXYToLatLonToRef(x: number, y: number, levelOfDetail: number, latLon?: IGeo2 | undefined): void;
    abstract getLatLonToPixelXYToRef(latitude: number, longitude: number, levelOfDetail: number, pixelXY?: ICartesian2): void;
    abstract getPixelXYToLatLonToRef(x: number, y: number, levelOfDetail: number, latLon?: IGeo2): void;
    abstract getTileXYToPixelXYToRef(x: number, y: number, pixelXY?: ICartesian2): void;
    abstract getPixelXYToTileXYToRef(x: number, y: number, tileXY?: ICartesian2): void;
}
