import { ICartesian2 } from "../geometry/geometry.interfaces";
import { IGeo2 } from "../geography/geography.interfaces";
import { ITileMetrics, ITileMetricsOptions, CellCoordinateReference } from "./tiles.interfaces";
export declare class TileMetricsOptions implements ITileMetricsOptions {
    static DefaultTileSize: number;
    static DefaultLOD: number;
    static DefaultMinLOD: number;
    static DefaultMaxLOD: number;
    static DefaultMinLatitude: number;
    static DefaultMaxLatitude: number;
    static DefaultMinLongitude: number;
    static DefaultMaxLongitude: number;
    static DefaultCellSize: number;
    static DefaultCoordinateReference: CellCoordinateReference;
    static DefaultOverlap: number;
    minLOD?: number;
    maxLOD?: number;
    minLatitude?: number;
    maxLatitude?: number;
    minLongitude?: number;
    maxLongitude?: number;
    tileSize?: number;
    cellSize?: number;
    cellCoordinateReference?: CellCoordinateReference;
    overlap?: number;
    static Shared: TileMetricsOptions;
    constructor(p: Partial<TileMetricsOptions>);
}
export declare class TileMetricsOptionsBuilder {
    _minLOD?: number;
    _maxLOD?: number;
    _minLatitude?: number;
    _maxLatitude?: number;
    _minLongitude?: number;
    _maxLongitude?: number;
    _tileSize?: number;
    _cellSize?: number;
    _cellCoordinateReference?: CellCoordinateReference;
    _overlap?: number;
    withTileSize(v?: number): TileMetricsOptionsBuilder;
    withCellSize(v?: number): TileMetricsOptionsBuilder;
    withCellCoordinateReference(v?: CellCoordinateReference): TileMetricsOptionsBuilder;
    withTOverlap(v?: number): TileMetricsOptionsBuilder;
    withMinLOD(v?: number): TileMetricsOptionsBuilder;
    withMaxLOD(v?: number): TileMetricsOptionsBuilder;
    withMinLatitude(v?: number): TileMetricsOptionsBuilder;
    withMaxLatitude(v?: number): TileMetricsOptionsBuilder;
    withMinLongitude(v?: number): TileMetricsOptionsBuilder;
    withMaxLongitude(v?: number): TileMetricsOptionsBuilder;
    build(): ITileMetricsOptions;
}
export declare abstract class AbstractTileMetrics implements ITileMetrics {
    _o: TileMetricsOptions;
    constructor(options?: Partial<TileMetricsOptions>);
    get options(): TileMetricsOptions;
    isCompatibleWith(metrics: ITileMetrics): boolean;
    mapSize(levelOfDetail: number): number;
    get minLOD(): number;
    get maxLOD(): number;
    get lodCount(): number;
    get minLatitude(): number;
    get maxLatitude(): number;
    get minLongitude(): number;
    get maxLongitude(): number;
    get tileSize(): number;
    get cellSize(): number;
    get cellCoordinateReference(): CellCoordinateReference;
    get overlap(): number;
    mapScale(latitude: number, levelOfDetail: number, pixelPerUnit: number): number;
    abstract groundResolution(latitude: number, levelOfDetail: number): number;
    abstract getLatLonToTileXY(latitude: number, longitude: number, levelOfDetail: number, tileXY?: ICartesian2 | undefined): ICartesian2;
    abstract getTileXYToLatLon(x: number, y: number, levelOfDetail: number, latLon?: IGeo2 | undefined): IGeo2;
    abstract getLatLonToPixelXY(latitude: number, longitude: number, levelOfDetail: number, pixelXY?: ICartesian2): ICartesian2;
    abstract getPixelXYToLatLon(x: number, y: number, levelOfDetail: number, latLon?: IGeo2): IGeo2;
    abstract getTileXYToPixelXY(x: number, y: number, pixelXY?: ICartesian2): ICartesian2;
    abstract getPixelXYToTileXY(x: number, y: number, tileXY?: ICartesian2): ICartesian2;
}
