import * as BABYLON from "@babylonjs/core";
import { VirtualDisplay } from "./display.virtual";
import { ICartesian2WithInfos, IPointerSource, IWheelSource } from "core/map/inputs";
import { Observable } from "core/events";
export declare class VirtualDisplayInputsSource implements IPointerSource, IWheelSource, BABYLON.IDisposable {
    _onPointerOverObservable?: Observable<ICartesian2WithInfos>;
    _onPointerEnterObservable?: Observable<ICartesian2WithInfos>;
    _onPointerOutObservable?: Observable<ICartesian2WithInfos>;
    _onPointerLeaveObservable?: Observable<ICartesian2WithInfos>;
    _onPointerMoveObservable?: Observable<ICartesian2WithInfos>;
    _onPointerDownObservable?: Observable<ICartesian2WithInfos>;
    _onPointerUpObservable?: Observable<ICartesian2WithInfos>;
    _onPointerCancelObservable?: Observable<ICartesian2WithInfos>;
    _onPointerGotCaptureObservable?: Observable<ICartesian2WithInfos>;
    _onPointerLostCaptureObservable?: Observable<ICartesian2WithInfos>;
    _onWheelObservable?: Observable<number>;
    _display: VirtualDisplay;
    _prePointerObserver: BABYLON.Nullable<BABYLON.Observer<BABYLON.PointerInfoPre>>;
    _currentPosition: BABYLON.Nullable<BABYLON.Vector2>;
    constructor(display: VirtualDisplay);
    get display(): VirtualDisplay;
    get onPointerOverObservable(): Observable<ICartesian2WithInfos>;
    get onPointerEnterObservable(): Observable<ICartesian2WithInfos>;
    get onPointerOutObservable(): Observable<ICartesian2WithInfos>;
    get onPointerLeaveObservable(): Observable<ICartesian2WithInfos>;
    get onPointerMoveObservable(): Observable<ICartesian2WithInfos>;
    get onPointerDownObservable(): Observable<ICartesian2WithInfos>;
    get onPointerUpObservable(): Observable<ICartesian2WithInfos>;
    get onPointerCancelObservable(): Observable<ICartesian2WithInfos>;
    get onPointerGotCaptureObservable(): Observable<ICartesian2WithInfos>;
    get onPointerLostCaptureObservable(): Observable<ICartesian2WithInfos>;
    get onWheelObservable(): Observable<number>;
    dispose(): void;
    protected _attach(): void;
    protected _onPrePointer(pi: BABYLON.PointerInfoPre): void;
    private _onPointerDown;
    private _onPointerUp;
    private _onPointerMove;
    private _onWheel;
    protected _getDisplayPosition(scene: BABYLON.Scene): BABYLON.Nullable<BABYLON.Vector3>;
    protected _pickFilter(mesh: BABYLON.Nullable<any>): boolean;
    protected _getScene(): BABYLON.Scene;
}
