import { Matrix, Mesh, Scene, TransformNode, Vector2, Vector3, VertexData } from "@babylonjs/core";
import { ICartesian3, ISize2, ISize3 } from "core/geometry";
import { VirtualDisplayInputsSource } from "./display.inputs.scene";
import { Observable, PropertyChangedEventArgs } from "core/events";
import { Unit } from "core/math";
import { IDisplay, IPhysicalDisplay } from "core/tiles";
export declare class VirtualDisplay implements IPhysicalDisplay {
    static QVGA: ISize2;
    static VGA: ISize2;
    static QHD: ISize2;
    static HD: ISize2;
    static WXGA: ISize2;
    static FullHD: ISize2;
    static UltraHD: ISize2;
    static UltraHD2: ISize2;
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<IDisplay, unknown>>;
    _worldTransform: TransformNode;
    _dimension: ISize3;
    _halfDimension: ISize3;
    _ppu: Vector3;
    _ratio: Vector3;
    _unit: Unit;
    _resolution: ISize3;
    _pointerSource: VirtualDisplayInputsSource;
    _node: Mesh;
    _center: ICartesian3;
    _inverseWorldMatrix?: Matrix;
    constructor(name: string, dimension: ISize2, resolution: ISize2, scene?: Mesh | Scene, unit?: Unit);
    get node(): Mesh;
    getScene(): Scene;
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<IDisplay, unknown>>;
    get width(): number;
    get height(): number;
    get ratio(): number;
    get pointerSource(): VirtualDisplayInputsSource;
    protected _buildVertexData(dimension: ISize2): VertexData;
    get context3D(): TransformNode;
    get resolution(): ISize3;
    get unit(): Unit;
    get dimension(): ISize3;
    get halfDimension(): ISize3;
    get pixelPerUnit(): ICartesian3;
    get dpi(): number;
    get aspectRatio(): ICartesian3;
    getPixelToRef0(pickedCoordinates: Vector2, pixel?: Vector2): Vector2;
    getXYZWorldVectors(): Array<Vector3>;
    dispose(doNotRecurse?: boolean, disposeMaterialAndTextures?: boolean): void;
}
