import { EventState, Observable, PropertyChangedEventArgs } from "../../events";
import { ILinkOptions, IPipelineMessageType, ITargetBlock, ITileConsumer, ITilePipelineLink } from "./tiles.pipeline.interfaces";
import { ITile } from "../tiles.interfaces";
import { ValidableBase } from "../../validable";
export declare class TileConsumerBase<T> extends ValidableBase implements ITileConsumer<T> {
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<unknown, unknown>> | undefined;
    _updatedObservable?: Observable<IPipelineMessageType<ITile<T>>>;
    _addedObservable?: Observable<IPipelineMessageType<ITile<T>>>;
    _removedObservable?: Observable<IPipelineMessageType<ITile<T>>>;
    _links: Array<ITilePipelineLink<ITile<T>>>;
    _name: string;
    constructor(id: string);
    get updatedObservable(): Observable<IPipelineMessageType<ITile<T>>>;
    get addedObservable(): Observable<IPipelineMessageType<ITile<T>>>;
    get removedObservable(): Observable<IPipelineMessageType<ITile<T>>>;
    linkTo(target: ITargetBlock<ITile<T>>, options?: ILinkOptions): void;
    unlinkFrom(target: ITargetBlock<ITile<T>>): ITilePipelineLink<ITile<T>> | undefined;
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<unknown, unknown>>;
    get name(): string;
    set name(name: string);
    added(eventData: IPipelineMessageType<ITile<T>>, eventState: EventState): void;
    removed(eventData: IPipelineMessageType<ITile<T>>, eventState: EventState): void;
    updated(eventData: IPipelineMessageType<ITile<T>>, eventState: EventState): void;
    dispose(): void;
    protected _onBeforeTileAdded(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onBeforeTileRemoved(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onBeforeTileUpdated(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onTileAdded(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onTileRemoved(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onTileUpdated(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onAfterTileAdded(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onAfterTileRemoved(eventData: Array<ITile<T>>, eventState: EventState): void;
    protected _onAfterTileUpdated(eventData: Array<ITile<T>>, eventState: EventState): void;
}
