import { Observable } from "../../events";
import { ITileAddress, ITileMetrics } from "../tiles.interfaces";
import { ILinkOptions, IPipelineMessageType, ITargetBlock, ITilePipelineLink, ITileView } from "./tiles.pipeline.interfaces";
import { Nullable } from "../../types";
import { ICartesian2, IBounds2 } from "../../geometry";
import { ITileNavigationState } from "../navigation";
import { Bearing } from "../../geography";
import { IDisplay } from "../map";
export declare class TileView implements ITileView {
    _addedObservable?: Observable<IPipelineMessageType<ITileAddress>>;
    _removedObservable?: Observable<IPipelineMessageType<ITileAddress>>;
    _updatedObservable?: Observable<IPipelineMessageType<ITileAddress>>;
    _activ: Map<string, ITileAddress>;
    _links: Array<ITilePipelineLink<ITileAddress>>;
    _id: string;
    constructor(id: string);
    get name(): string;
    dispose(): void;
    get addedObservable(): Observable<IPipelineMessageType<ITileAddress>>;
    get removedObservable(): Observable<IPipelineMessageType<ITileAddress>>;
    get updatedObservable(): Observable<IPipelineMessageType<ITileAddress>>;
    linkTo(target: ITargetBlock<ITileAddress>, options?: ILinkOptions<ITileAddress>): void;
    unlinkFrom(target: ITargetBlock<ITileAddress>): ITilePipelineLink<ITileAddress> | undefined;
    setContext(state: Nullable<ITileNavigationState>, display: Nullable<IDisplay>, metrics: ITileMetrics, dispatchEvent?: boolean): void;
    protected _doValidateContext(state: Nullable<ITileNavigationState>, display: Nullable<IDisplay>, metrics: ITileMetrics, activAddresses: Map<string, ITileAddress>, dispatchEvent?: boolean): void;
    private _doClearContext;
    protected _getRectangle(center: ICartesian2, w: number, h: number, scale: number, azimuth?: Bearing): IBounds2;
    protected _getTileRectangle(a: ITileAddress, metrics: ITileMetrics, center: ICartesian2, azimuth: Bearing): IBounds2;
    protected _rotatePointsArround(center: ICartesian2, azimuth: Bearing, ...points: ICartesian2[]): IterableIterator<ICartesian2>;
    protected _rotatePointArround<R extends ICartesian2>(x: number, y: number, center: ICartesian2, azimuth: Bearing, target?: R): R;
}
