import { Observable, Observer, PropertyChangedEventArgs } from "../../events";
import { ITileNavigationState } from "../navigation";
import { ITileDisplay, ITileMap, ITileMapLayer } from "./tiles.map.interfaces";
import { Nullable } from "../../types";
import { IGeo2 } from "../../geography/geography.interfaces";
import { ValidableBase } from "../../validable";
interface ITileMapLayerContainer<T> {
    layer: ITileMapLayer<T>;
    validationObserver: Nullable<Observer<boolean>>;
}
export declare class TileMapBase<T> extends ValidableBase implements ITileMap<T> {
    _layerAddedObservable?: Observable<ITileMapLayer<T>>;
    _layerRemovedObservable?: Observable<ITileMapLayer<T>>;
    protected _name: string;
    protected _display: Nullable<ITileDisplay>;
    protected _navigation: ITileNavigationState;
    protected _layers?: Array<ITileMapLayerContainer<T>>;
    protected _orderedLayers?: ITileMapLayer<T>[];
    _navigationUpdatedObserver?: Nullable<Observer<ITileNavigationState>>;
    _displayPropertyObserver?: Nullable<Observer<PropertyChangedEventArgs<ITileDisplay, unknown>>>;
    constructor(name: string, display?: Nullable<ITileDisplay>, nav?: ITileNavigationState);
    get layerAddedObservable(): Observable<ITileMapLayer<T>>;
    get layerRemovedObservable(): Observable<ITileMapLayer<T>>;
    get display(): Nullable<ITileDisplay>;
    get navigation(): ITileNavigationState;
    getLayers(predicate?: (l: ITileMapLayer<T>) => boolean, sorted?: boolean): IterableIterator<ITileMapLayer<T>>;
    getOrderedLayers(predicate?: (l: ITileMapLayer<T>) => boolean): IterableIterator<ITileMapLayer<T>>;
    addLayer(layer: ITileMapLayer<T>): void;
    removeLayer(layer: ITileMapLayer<T>): void;
    dispose(): void;
    setView(center: IGeo2 | Array<number>, zoom?: number, rotation?: number): TileMapBase<T>;
    zooming(delta: number): TileMapBase<T>;
    zoomIn(delta: number): TileMapBase<T>;
    zoomOut(delta: number): TileMapBase<T>;
    translatePixel(tx: number, ty: number): TileMapBase<T>;
    translate(lat: IGeo2 | Array<number> | number, lon?: number): TileMapBase<T>;
    rotate(r: number): TileMapBase<T>;
    private _addSortedLayer;
    private _removeSortedLayer;
    private _onNavigationUpdatedInternal;
    private _updateLayersWithDisplayAndNavigation;
    private _onDisplayPropertyChanged;
    private _bindDisplay;
    private _bindNavigation;
    private _updateNavigationBounds;
    private _onLayerAddedInternal;
    private _onLayerRemovedInternal;
    private _onLayerValidationChanged;
    protected _beforeValidate(): void;
    protected _onDisplayUnbinded(display: Nullable<ITileDisplay>): void;
    protected _onDisplayBinded(display: Nullable<ITileDisplay>): void;
    protected _onNavigationUnbinded(nav?: ITileNavigationState): void;
    protected _onNavigationBinded(nav?: ITileNavigationState): void;
    protected _onNavigationUpdated(nav?: ITileNavigationState): void;
    protected _onDisplayResized(display: ITileDisplay): void;
    protected _onDisplayTranslated(display: ITileDisplay): void;
    protected _onLayerAdded(layer: ITileMapLayer<T>): void;
    protected _onLayerRemoved(layer: ITileMapLayer<T>): void;
}
export {};
