import { EventState, Observable, Observer, PropertyChangedEventArgs } from "../../events";
import { ITileMetrics } from "../tiles.interfaces";
import { ITileNavigationState } from "../navigation";
import { ITileDisplay, ITileMap, ITileMapLayer } from "./tiles.map.interfaces";
import { Nullable } from "../../types";
import { IGeo2 } from "../../geography/geography.interfaces";
import { TileConsumerBase } from "../pipeline";
export declare class TileMapBase<T, L extends ITileMapLayer<T>> extends TileConsumerBase<T> implements ITileMap<T, L> {
    _layerAddedObservable?: Observable<L>;
    _layerRemovedObservable?: Observable<L>;
    protected _display: Nullable<ITileDisplay>;
    protected _navigation: ITileNavigationState;
    protected _layers?: Array<L>;
    protected _zIndexOrderedLayers?: Array<L>;
    _navigationUpdatedObserver?: Nullable<Observer<ITileNavigationState>>;
    _displayPropertyObserver?: Nullable<Observer<PropertyChangedEventArgs<ITileDisplay, unknown>>>;
    constructor(name: string, display?: Nullable<ITileDisplay>, nav?: ITileNavigationState);
    get layerAddedObservable(): Observable<L>;
    get layerRemovedObservable(): Observable<L>;
    get display(): Nullable<ITileDisplay>;
    get navigation(): ITileNavigationState;
    set navigation(nav: ITileNavigationState);
    getLayers(predicate?: (l: L) => boolean, sorted?: boolean): IterableIterator<L>;
    getOrderedLayers(predicate?: (l: L) => boolean): IterableIterator<L>;
    addLayer(layer: L): void;
    removeLayer(layer: L): void;
    dispose(): void;
    setViewMap(center: IGeo2 | Array<number>, zoom?: number, rotation?: number): TileMapBase<T, L>;
    zoomMap(delta: number): TileMapBase<T, L>;
    zoomInMap(delta: number): TileMapBase<T, L>;
    zoomOutMap(delta: number): TileMapBase<T, L>;
    translatePixelMap(tx: number, ty: number, metrics?: ITileMetrics): TileMapBase<T, L>;
    translateMap(lat: IGeo2 | Array<number> | number, lon?: number): TileMapBase<T, L>;
    rotateMap(r: number): TileMapBase<T, L>;
    private _addSortedLayer;
    private _removeSortedLayer;
    private _onNavigationUpdatedInternal;
    private _updateLayersWithDisplayAndNavigation;
    private _onDisplayPropertyChanged;
    private _bindDisplay;
    private _bindNavigation;
    private _updateNavigationBounds;
    private _onLayerAddedInternal;
    private _onLayerRemovedInternal;
    protected _onLayerValidationChanged(valid: boolean, state: EventState): void;
    protected _beforeValidate(): void;
    protected _onDisplayUnbinded(display: Nullable<ITileDisplay>): void;
    protected _onDisplayBinded(display: Nullable<ITileDisplay>): void;
    protected _onNavigationUnbinded(nav?: ITileNavigationState): void;
    protected _onNavigationBinded(nav?: ITileNavigationState): void;
    protected _onNavigationUpdated(nav?: ITileNavigationState): void;
    protected _onDisplayResized(display: ITileDisplay): void;
    protected _onDisplayTranslated(display: ITileDisplay): void;
    protected _onLayerAdded(layer: L): void;
    protected _onLayerRemoved(layer: L): void;
}
