import { Observable, PropertyChangedEventArgs } from "../../events";
import { ITile, ITileAddress, ITileCollection, ITileMetrics } from "../tiles.interfaces";
import { ITileMapLayer, ITileMapLayerOptions, ITileMapLayerContainer, IHasTileMapLayerContainer, LayerRenderFn } from "./tiles.map.interfaces";
import { ITransformBlock } from "../pipeline/tiles.pipeline.interfaces";
export declare abstract class AbstractTileMapLayer<T> implements ITileMapLayer<T> {
    _name: string;
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<unknown, unknown>>;
    _zindex: number;
    _zoomOffset: number;
    _attribution?: string;
    _enabled: boolean;
    _provider: ITransformBlock<ITileAddress, ITile<T>>;
    _draw?: LayerRenderFn<T>;
    _drawTarget?: any;
    constructor(name: string, provider: ITransformBlock<ITileAddress, ITile<T>>, options?: ITileMapLayerOptions<T>, enabled?: boolean);
    get draw(): LayerRenderFn<T> | undefined;
    get drawTarget(): any;
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<unknown, unknown>>;
    get name(): string;
    get provider(): ITransformBlock<ITileAddress, ITile<T>>;
    get zindex(): number;
    set zindex(zindex: number);
    get zoomOffset(): number;
    set zoomOffset(zoomOffset: number);
    get attribution(): string | undefined;
    set attribution(attribution: string | undefined);
    get enabled(): boolean;
    set enabled(enabled: boolean);
    addTo(map: ITileMapLayerContainer<T, ITileMapLayer<T>> | IHasTileMapLayerContainer<T, ITileMapLayer<T>>): ITileMapLayer<T>;
    dispose(): void;
    abstract get metrics(): ITileMetrics;
    abstract get activTiles(): ITileCollection<T>;
}
