import { Observable, PropertyChangedEventArgs } from "../../events";
import { ITile, ITileAddress, ITileDatasource, ITileMetrics, ITileProvider, TileContentType } from "../tiles.interfaces";
import { ITileMapLayer, ITileMapLayerOptions, ITileMapLayerContainer, IHasTileMapLayerContainer, LayerRenderFn } from "./tiles.map.interfaces";
import { IMemoryCache } from "../../cache";
import { Nullable } from "../../types";
export declare class TileMapLayer<T> implements ITileMapLayer<T> {
    _name: string;
    _zindex: number;
    _zoomOffset: number;
    _attribution?: string;
    _enabled: boolean;
    _draw?: LayerRenderFn<T>;
    _drawTarget?: any;
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<unknown, unknown>>;
    _provider: ITileProvider<T>;
    constructor(name: string, provider: ITileProvider<T> | ITileDatasource<T, ITileAddress>, options?: ITileMapLayerOptions<T>, enabled?: boolean);
    get activTiles(): Array<Nullable<ITile<T>>>;
    get metrics(): ITileMetrics;
    get provider(): ITileProvider<T>;
    get drawFn(): LayerRenderFn<T> | undefined;
    get drawTarget(): any;
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<unknown, unknown>>;
    get name(): string;
    get zindex(): number;
    set zindex(zindex: number);
    get zoomOffset(): number;
    set zoomOffset(zoomOffset: number);
    get attribution(): string | undefined;
    set attribution(attribution: string | undefined);
    get enabled(): boolean;
    set enabled(enabled: boolean);
    addTo(map: ITileMapLayerContainer<T, ITileMapLayer<T>> | IHasTileMapLayerContainer<T, ITileMapLayer<T>>): ITileMapLayer<T>;
    dispose(): void;
    protected _buildProvider(provider: ITileDatasource<T, ITileAddress>, cache?: IMemoryCache<string, TileContentType<T>>, type?: new (...args: any[]) => ITile<T>): ITileProvider<T>;
}
