import { EventState, Observable, Observer, PropertyChangedEventArgs } from "../../events";
import { ITileMetrics } from "../tiles.interfaces";
import { ITileNavigationState } from "../navigation";
import { IDisplay, ITileMap, ITileMapLayer, ITileMapLayerContainer, ITileMapLayerView, ITileMapLayerViewContainer } from "./tiles.map.interfaces";
import { Nullable } from "../../types";
import { IGeo2 } from "../../geography/geography.interfaces";
import { ITileView } from "../pipeline";
import { ValidableBase } from "../../validable";
import { IOrderedCollection } from "../../collections/collections.interfaces";
export declare class TileMapBase<T> extends ValidableBase implements ITileMap<T> {
    static readonly DISPLAY_PROPERTY_NAME: string;
    static readonly NAVIGATION_PROPERTY_NAME: string;
    protected _display: Nullable<IDisplay>;
    protected _navigation: Nullable<ITileNavigationState>;
    protected _view: ITileView;
    protected _layerAddedObserver: Nullable<Observer<Array<ITileMapLayer<T>>>>;
    protected _layerRemovedObserver: Nullable<Observer<Array<ITileMapLayer<T>>>>;
    protected _layers: ITileMapLayerContainer<T>;
    protected _layerViewAddedObserver: Nullable<Observer<Array<ITileMapLayerView<T>>>>;
    protected _layerViewRemovedObserver: Nullable<Observer<Array<ITileMapLayerView<T>>>>;
    protected _layerViews: ITileMapLayerViewContainer<T>;
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<ITileMap<T>, unknown>>;
    _displayPropertyObserver?: Nullable<Observer<PropertyChangedEventArgs<IDisplay, unknown>>>;
    _navigationPropertyObserver?: Nullable<Observer<PropertyChangedEventArgs<ITileNavigationState, unknown>>>;
    _navigationValidableObserver?: Nullable<Observer<boolean>>;
    _navInstanceCache?: ITileNavigationState;
    constructor(display?: Nullable<IDisplay>, nav?: Nullable<ITileNavigationState>, container?: ITileMapLayerContainer<T>);
    get layers(): ITileMapLayerContainer<T>;
    get layerViews(): ITileMapLayerViewContainer<T>;
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<ITileMap<T>, unknown>>;
    get display(): Nullable<IDisplay>;
    set display(value: Nullable<IDisplay>);
    get navigation(): Nullable<ITileNavigationState>;
    set navigation(value: Nullable<ITileNavigationState>);
    get view(): ITileView;
    dispose(): void;
    setViewMap(center: IGeo2 | Array<number>, zoom?: number, rotation?: number): TileMapBase<T>;
    zoomMap(delta: number): TileMapBase<T>;
    zoomInMap(delta: number): TileMapBase<T>;
    zoomOutMap(delta: number): TileMapBase<T>;
    translateUnitsMap(tx: number, ty: number, metrics?: ITileMetrics): TileMapBase<T>;
    translateMap(lat: IGeo2 | Array<number> | number, lon?: number): TileMapBase<T>;
    rotateMap(r: number): TileMapBase<T>;
    get isValid(): boolean;
    protected _doValidate(): void;
    protected _onLayerAdded(eventData: Array<ITileMapLayer<T>>, eventstate: EventState): void;
    protected _onLayerRemoved(eventData: Array<ITileMapLayer<T>>, eventstate: EventState): void;
    protected _onLayerViewAdded(eventData: Array<ITileMapLayerView<T>>, eventstate: EventState): void;
    protected _onLayerViewRemoved(eventData: Array<ITileMapLayerView<T>>, eventstate: EventState): void;
    protected _onNavigationValidationChanged(event: boolean, state: EventState): void;
    protected _onDisplayPropertyChanged(event: PropertyChangedEventArgs<IDisplay, unknown>, state: EventState): void;
    protected _onNavigationPropertyChanged(event: PropertyChangedEventArgs<ITileNavigationState, unknown>, state: EventState): void;
    private _bindDisplay;
    private _bindNavigation;
    protected _createLayerContainer(): ITileMapLayerContainer<T>;
    protected _createLayerViewContainer(layers: ITileMapLayerContainer<T>): IOrderedCollection<ITileMapLayerView<T>>;
    protected _createLayerView(layer: ITileMapLayer<T>): ITileMapLayerView<T>;
    protected _onDisplayUnbinded(display: Nullable<IDisplay>): void;
    protected _onDisplayBinded(display: Nullable<IDisplay>): void;
    protected _onNavigationUnbinded(nav: Nullable<ITileNavigationState>): void;
    protected _onNavigationBinded(nav: Nullable<ITileNavigationState>): void;
    protected _onNavigationUpdated(nav: ITileNavigationState): void;
    protected _onDisplayResized(display: IDisplay): void;
    protected _onDisplayTranslated(display: IDisplay): void;
    protected _buildNavigationState(): ITileNavigationState;
    protected _buildView(): ITileView;
    private _createLayerContainerInternal;
    private _createLayerViewContainerInternal;
    private _createLayerViewInternal;
}
