import { Observable, PropertyChangedEventArgs } from "../../events";
import { ITileAddress, ITileContentProvider, ITileDatasource, ITileMetrics, TileContentType } from "../tiles.interfaces";
import { ITileMapLayer, ITileMapLayerOptions, ITileMapLayerContainer, IHasTileMapLayerContainer, LayerRenderFn } from "./tiles.map.interfaces";
import { IMemoryCache } from "../../cache";
import { IWeighted } from "../../collections/collections.interfaces";
export declare class TileMapLayer<T> implements ITileMapLayer<T> {
    _name: string;
    _weight: number;
    _zoomOffset: number;
    _attribution?: string;
    _enabled: boolean;
    _draw?: LayerRenderFn<T>;
    _drawTarget?: any;
    _weightChangedObservable?: Observable<IWeighted>;
    _propertyChangedObservable?: Observable<PropertyChangedEventArgs<unknown, unknown>>;
    _provider: ITileContentProvider<T>;
    constructor(name: string, provider: ITileContentProvider<T> | ITileDatasource<T, ITileAddress>, options?: ITileMapLayerOptions<T>, enabled?: boolean);
    get metrics(): ITileMetrics;
    get provider(): ITileContentProvider<T>;
    get drawFn(): LayerRenderFn<T> | undefined;
    get drawTarget(): any;
    get propertyChangedObservable(): Observable<PropertyChangedEventArgs<unknown, unknown>>;
    get weightChangedObservable(): Observable<IWeighted>;
    get name(): string;
    get weight(): number;
    set weight(zindex: number);
    get zoomOffset(): number;
    set zoomOffset(zoomOffset: number);
    get attribution(): string | undefined;
    set attribution(attribution: string | undefined);
    get enabled(): boolean;
    set enabled(enabled: boolean);
    addTo(map: ITileMapLayerContainer<T> | IHasTileMapLayerContainer<T>): ITileMapLayer<T>;
    dispose(): void;
    protected _buildProvider(dataSource: ITileDatasource<T, ITileAddress>, cache?: IMemoryCache<string, TileContentType<T>>): ITileContentProvider<T>;
}
